define("dojo/dom dojo/dom-attr dojo/_base/event dojo/keys dojo/on dojo/has dojo/when esri/dijit/HomeButton".split(" "),function(k,h,l,d,e,q,D,r){function t(b){e(b,"layers-add-result",function(a){var c=a.target;a=a.target.container;a.mapReference=c;var b=k.byId(c.id+"_gc");b.tabIndex="-1";h.set(b,"focusable","false");h.set(a,"focusable","true");a.tabIndex="0";c.disableScrollWheelZoom();c.disableDoubleClickZoom();c.disableKeyboardNavigation();0<=h.get(a,"class").indexOf("comparisonMap")?(u(a),v(c),
c=k.byId(c.id+"_zoom_slider"),c.childNodes[0].title="en"===dojoConfig.locale?"Zoom in":"Agrandir",c.childNodes[1].title="en"===dojoConfig.locale?"Zoom out":"R\u00e9tr\u00e9cir",h.set(c,"focusable","true"),a=q("ie")?"keydown, click":"keydown, mousedown",a=e.pausable(c,a,w)):(x(a),c=k.byId(c.id+"_zoom_slider"),c.childNodes[0].title="en"===dojoConfig.locale?"Zoom in":"Agrandir",c.childNodes[1].title="en"===dojoConfig.locale?"Zoom out":"R\u00e9tr\u00e9cir",h.set(c,"focusable","true"),a=q("ie")?"keydown, click":
"keydown, mousedown",a=e.pausable(c,a,y));z(c,a);a.pause()})}function u(b){var a=e.pausable(b,"keydown",function(a){var b=a.currentTarget.parentElement.firstElementChild,d=b.nextElementSibling,e=d.nextElementSibling;n(a,b.mapReference);n(a,d.mapReference);n(a,e.mapReference)});p(b,a);a.pause()}function x(b){var a=e.pausable(b,"keydown",function(a){n(a,a.currentTarget.mapReference)});p(b,a);a.pause()}function p(b,a){e(b,"mouseenter",function(a){a.target.focus()});e(b,"focus",function(b){b.target.style.outline=
"medium solid lightblue";a.resume()});e(b,"mouseleave",function(a){a.target.blur()});e(b,"blur",function(b){b.target.style.outline="none";a.pause()})}function n(b,a){var c=!0;switch(b.keyCode){case d.HOME:case d.NUMPAD_7:a._fixedPan(-.05*a.width,-.05*a.width);break;case d.NUMPAD_8:case d.UP_ARROW:a._fixedPan(0,-.05*a.width);break;case d.PAGE_UP:case d.NUMPAD_9:a._fixedPan(.05*a.width,-.05*a.width);break;case d.NUMPAD_6:case d.RIGHT_ARROW:a._fixedPan(.05*a.width,0);break;case d.PAGE_DOWN:case d.NUMPAD_3:a._fixedPan(.05*
a.width,.05*a.width);break;case d.NUMPAD_2:case d.DOWN_ARROW:a._fixedPan(0,.05*a.width);break;case d.END:case d.NUMPAD_1:a._fixedPan(-.05*a.width,.05*a.width);break;case d.NUMPAD_4:case d.LEFT_ARROW:a._fixedPan(-.05*a.width,0);break;case d.NUMPAD_PLUS:!1===b.ctrlKey&&a.setLevel(a.getLevel()+1);break;case d.NUMPAD_MINUS:!1===b.ctrlKey&&a.setLevel(a.getLevel()-1);break;default:c=!1}c&&l.stop(b)}function z(b,a){var c;for(c=0;c<b.childNodes.length;c++)b.childNodes[c].tabIndex=0,e(b.childNodes[c],"mouseenter",
function(a){a.target.focus()}),e(b.childNodes[c],"focus",function(b){b.target.style.outline="medium solid lightblue";a.resume()}),e(b.childNodes[c],"mouseleave",function(a){a.target.blur()}),e(b.childNodes[c],"blur",function(b){b.target.style.outline="none";a.pause()})}function y(b){var a=b.currentTarget.parentElement.parentElement;switch(b.keyCode){case d.ENTER:case d.NUMPAD_ENTER:case d.SPACE:f(b,a.mapReference)}}function w(b){var a=b.currentTarget.parentElement.parentElement.parentElement.firstElementChild,
c=a.nextElementSibling,m=c.nextElementSibling;switch(b.type){case "keydown":switch(b.keyCode){case d.ENTER:case d.NUMPAD_ENTER:case d.SPACE:f(b,a.mapReference),f(b,c.mapReference),f(b,m.mapReference)}break;case "click":case "mousedown":switch(b.currentTarget.parentElement.parentElement.id){case a.id:f(b,c.mapReference);f(b,m.mapReference);break;case c.id:f(b,a.mapReference);f(b,m.mapReference);break;case m.id:f(b,a.mapReference),f(b,c.mapReference)}}}function f(b,a){var c=!0;switch(b.target.className){case "esriSimpleSliderIncrementButton":a.setZoom(a.getZoom()+
1);break;case "esriSimpleSliderDecrementButton":a.setZoom(a.getZoom()-1);break;default:c=!1}c&&l.stop(b)}function v(b){b.on("mouse-up",function(a){a=this.container.parentElement.firstElementChild;var b=a.nextElementSibling,d=b.nextElementSibling,g=this.extent;switch(this.id){case a.id:b.mapReference.setExtent(g);d.mapReference.setExtent(g);break;case b.id:a.mapReference.setExtent(g);d.mapReference.setExtent(g);break;case d.id:a.mapReference.setExtent(g),b.mapReference.setExtent(g)}})}function A(b,
a,c){var d=k.byId(b+"_root"),g=document.createElement("div");g.className="HomeButton";g.id="homebutton_"+b;e(a,"load",function(b){d.appendChild(g);var f=new r({map:a,theme:"comparemap"==c?"HomeButtonForCompareMap":"HomeButton"},g);f.startup();b=f.domNode;b.homeButtonReference=f;h.set(b,"focusable","true");b.tabIndex="0";f=null;f="comparemap"==c?e.pausable(b,"keydown, mousedown",B):e.pausable(b,"keydown",C);p(b,f);f.pause()})}function B(b){var a=!0;switch(b.type){case "keydown":switch(b.keyCode){case d.ENTER:case d.NUMPAD_ENTER:case d.SPACE:var c=
b.currentTarget.homeButtonReference,e=b.currentTarget.parentElement.parentElement.parentElement,e=e.firstElementChild,g=e.nextElementSibling,f=g.nextElementSibling;e.mapReference.setExtent(c.extent);g.mapReference.setExtent(c.extent);f.mapReference.setExtent(c.extent);break;default:a=!1}break;case "mousedown":switch(c=b.currentTarget.homeButtonReference,e=b.currentTarget.parentElement.parentElement.parentElement,e=e.firstElementChild,g=e.nextElementSibling,f=g.nextElementSibling,b.currentTarget.parentElement.parentElement.id){case e.id:g.mapReference.setExtent(c.extent);
f.mapReference.setExtent(c.extent);break;case g.id:e.mapReference.setExtent(c.extent);f.mapReference.setExtent(c.extent);break;case f.id:e.mapReference.setExtent(c.extent),g.mapReference.setExtent(c.extent)}}a&&l.stop(b)}function C(b){var a=!0;switch(b.keyCode){case d.ENTER:case d.NUMPAD_ENTER:case d.SPACE:b.currentTarget.parentElement.parentElement.mapReference.setExtent(b.currentTarget.homeButtonReference.extent);break;default:a=!1}a&&l.stop(b)}return{setEventsForMaps:function(b){t(b)},addEsriHomeButton:function(b,
a){A(b.id,b,a.type)}}});
