define("dojo/dom dojo/query dojo/dom-attr dojo/dom-style dojo/_base/array dojo/store/Memory dojo/on dojo/date/locale dojo/_base/Deferred dojox/validate/_base dijit/Toolbar dijit/form/Textarea esri/map esri/TimeExtent esri/dijit/TimeSlider esri/layers/LayerTimeOptions esri/layers/TimeInfo esri/layers/ArcGISDynamicMapServiceLayer esri/layers/ArcGISImageServiceLayer esri/layers/FeatureLayer esri/request esri/tasks/query esri/tasks/QueryTask dojo/NodeList-traverse".split(" "),function(C,m,x,T,p,U,V,u,
W,X,D,E,Y,F,G,Z,aa,H,I,J,y,ba,ca){function K(a){if("undefined"!==typeof a){var b=a.url,c=a.timeInfo.startTimeField,e=a.timeInfo.endTimeField,d=new Date,f=d.getTime()+" = "+d.getTime();switch(!0){case a instanceof J:v(a,b,f,c,e);break;case a instanceof H:d=L(a.visibleLayers);-1<d?(b=b+"/"+d,y({url:b,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}).then(function(d){if(!1===h(d.timeInfo)){var k=d.fields.filter(function(a,b,c){return"esriFieldTypeDate"===a.type});!1===h(k)&&(p.forEach(k,
function(a,b,f){switch(!0){case a.name===d.timeInfo.startTimeField:c=d.timeInfo.startTimeField;break;case a.name===d.timeInfo.endTimeField:e=d.timeInfo.endTimeField}}),h(c)&&(c=e),h(c)&&h(e)&&(c=k[0].name,e=h(k[1])?null:k[1].name));v(a,b,f,c,e)}else console.log("To show the time slider ensure the layer is time enabled and is the first visible layer.")},function(a){console.log("Error acquiring time info for layer: "+a.message)})):console.log("ErrorLayerNotVisible");break;case a instanceof I:v(a,b,
f,c,e);break;default:console.log("Unable to acquire time info for this layer type")}}}function v(a,b,c,e,d){!1===h(e)?M(a,b,c,e,d):(a=r(),z(a))}function M(a,b,c,e,d){var f=h(d)||e===d?[e]:[e,d];y({url:b+"/query",content:{f:"json",where:c,returnGeometry:!1,spatialRel:"esriSpatialRelIntersects",outFields:f,orderByFields:e,returnDistinctValues:!0},handleAs:"json",callbackParamName:"callback"}).then(function(b){if(h(b))return console.log("no records returned"),!1;var c=p.filter(b.fields,function(a){if("esriFieldTypeDate"===
a.type)return a});!1===h(b.features[0].attributes[e])&&"number"===typeof b.features[0].attributes[e]&&0<c.length?(c=b.features,b=!1===h(b.features[0].attributes[d])&&"number"===typeof b.features[0].attributes[d]?r(a,c,e,d):r(a,c,e)):b=r();z(a,b)},function(a){console.log("general query error")})}function r(a,b,c,e){var d=null,f=null,g=null,k=null,n=null,q=[],l=d=null,k=null;switch(arguments.length-1){case 2:d=new Date(b[0].attributes[c]);f=new Date(b[b.length-1].attributes[c]);l=f-d;n=new Date(b[0].attributes[c]);
q.push(n);for(i=1;i<b.length;i++)n=new Date(b[i].attributes[c]),q.push(n),g=q[i]-q[i-1],l>g&&0<g&&(l=g);break;case 3:d=new Date(b[0].attributes[c]);f=new Date(b[b.length-1].attributes[c]);l=f-d;p.forEach(b,function(a,b,d){n=new Date(a.attributes[c]);q.push(n);a=new Date(a.attributes[e])-n;l>a&&0<a&&(l=a)});break;default:d=a.timeInfo.timeExtent.startTime,f=a.timeInfo.timeExtent.endTime,l=f-d}!1===h(a.timeInfo.defaultTimeIntervalUnits)?(g=a.timeInfo.defaultTimeInterval,k=a.timeInfo.defaultTimeIntervalUnits):
!1===h(a.timeInfo.timeTimeIntervalUnits)?(g=a.timeInfo.timeInterval,k=a.timeInfo.timeIntervalUnits):(k=N(l),g=k.interval,k=k.units);d=new F(d,f);return{endTimeField:e,interval:g,looping:!0,singleThumbAsTimeInstant:!0,startTimeField:c,esriTimeExtent:d,timestops:q,thumbCount:1,thumbMovingRate:1500,units:k}}function z(a,b){var c=a._map;C.byId(c.id);var e=m(".timePanel",c.id)[0],d=m(".esriTimeSlider",c.id)[0],f=new G({},d.id);c.setTimeSlider(f);f.setThumbCount(b.thumbCount);h(b.timestops)?(f.createTimeStopsByTimeInterval(b.esriTimeExtent,
b.interval,b.units),f.timeStopsUtc=A(f.timeStops)):(f._timeIntervalUnits=b.units,f.setTimeStops(b.timestops),f.timeStopsUtc=A(b.timestops));f.setTickCount([f._numStops]);f.setThumbIndexes([f._numStops-1]);f.setThumbMovingRate(b.thumbMovingRate);f.singleThumbAsTimeInstant(b.singleThumbAsTimeInstant);f.setLoop(b.looping);d=O(f,b,e);f.setLabels(d);f.on("time-extent-change",function(a){var b=w(f._timeIntervalUnits,t(a.startTime));m("#timeSliderPanelDiv .dijitSliderImageHandleH").forEach(function(a){x.set(a,
"aria-valuetext",b)})});d=m(".timeToolbar",c.id);if(!1===h(d)){var d=new D({id:e.id+"_toolbar","class":"timeToolbar",tabIndex:-1},d[0].id),g=new E({id:e.id+"_textarea","class":"timeTextualDisplay",disabled:"disabled",tabIndex:-1,value:""});d.addChild(g);f.on("time-extent-change",function(a){m("#"+this.id).siblings(".timeToolbar").children(".timeTextualDisplay")[0].value=w(this._timeIntervalUnits,t(a.startTime))});c.y_shift=95}else switch(f._timeIntervalUnits){case "esriTimeUnitsCenturies":case "esriTimeUnitsDecades":case "esriTimeUnitsYears":c.y_shift=
45;break;default:c.y_shift=65}x.set(e,"style","height: "+c.y_shift+"px !important;");c.position.y+=c.y_shift;c.on("reposition",function(a){a.target.position.y+=a.target.y_shift});f.startup();m(".esriTimeSlider .dijitButtonContents").forEach(function(a){a.tabIndex="0";a.parentNode.nextSibling.title=a.title});m(".esriTimeSlider .dijitSliderImageHandleH").forEach(function(a){a.title="en"==dojoConfig.locale?"Time slider thumb control":"Commande au pouce pour curseur temporel";a.tabIndex="0"})}function A(a){var b=
[];p.forEach(a,function(a,e,d){b.push(t(a))});return b}function t(a){!1===a instanceof Date&&(a=new Date(a));return new Date(a.getUTCFullYear(),a.getUTCMonth(),a.getUTCDate(),a.getUTCHours(),a.getUTCMinutes(),a.getUTCSeconds(),a.getUTCMilliseconds())}function w(a,b){var c="";switch(a){case "esriTimeUnitsCenturies":case "esriTimeUnitsDecades":case "esriTimeUnitsYears":c=u.format(b,{selector:"date",datePattern:"yyyy"});break;case "esriTimeUnitsMonths":case "esriTimeUnitsWeeks":case "esriTimeUnitsDays":c=
u.format(b,{selector:"date",datePattern:"d MMM yyyy"});break;case "esriTimeUnitsMilliseconds":c=b.getTime().toString();break;default:c=u.format(b,{selector:"time",timePattern:"H:m:s d MMM yyyy"})}return c}function O(a,b,c){c=a._numStops;var e=0;switch(!0){case 12>=c:e=1;break;case 12<c&&24>=c:e=2;break;case 24<c&&48>=c:e=3;break;case 48<c&&96>=c:e=5;break;case 96<c&&192>=c:e=10;break;case 192<c&&384>=c:e=20;break;default:e=30}return p.map(a.timeStops,function(a,c){var g="";0!==c%e?g=B():(g=w(b.units,
t(a)),g=B(g));return g})}function B(a){var b="";switch(arguments.length){case 0:b="'<br/>";break;default:b="|<br/>"+a.replace(/ /g,"<br/>")}return b}function N(a){var b,c={};switch(!0){case 31104E8<=a:a=Math.round(a/31104E8);b="esriTimeUnitsCenturies";break;case 31104E7<=a:a=1;b="esriTimeUnitsDecades";break;case 31104E6<=a:a=1;b="esriTimeUnitsYears";break;case 24192E5<=a:a=1;b="esriTimeUnitsMonths";break;case 6048E5<=a:a=1;b="esriTimeUnitsWeeks";break;case 864E5<=a:a=1;b="esriTimeUnitsDays";break;
case 36E5<=a:a=1;b="esriTimeUnitsHours";break;case 6E4<=a:a=1;b="esriTimeUnitsMinutes";break;case 1E3<=a:a=1;b="esriTimeUnitsSeconds";break;default:a=1,b="esriTimeUnitsMilliseconds"}c.units=b;c.interval=a;return c}function h(a){var b=0,c;if("number"==typeof a||"boolean"==typeof a)return!1;if("undefined"==typeof a||null===a)return!0;if("undefined"!=typeof a.length)return 0==a.length;for(c in a)a.hasOwnProperty(c)&&b++;return 0==b}function L(a){for(var b=a.length,c=Infinity;b--;)a[b]<c&&(c=a[b]);return c}
var P="Dimanche Lundi Mardi Mercredi Jeudi Vendredi Samedi".split(" "),Q="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),R="Janvier F\u00e9vrier Mars Avril Mai Juin Juillet Ao\u00fbt Septembre Octobre Novembre D\u00e9cembre".split(" "),S="January February March April May June July August September October November December".split(" ");Date.prototype.getDayName=function(a){var b="en"==dojoConfig.locale?Q:P;return a?b[this.getUTCDay()].substr(0,3):b[this.getUTCDay()]};Date.prototype.getMonthName=
function(a){var b="en"==dojoConfig.locale?S:R;return a?b[this.getUTCMonth()].substr(0,3):b[this.getUTCMonth()]};return{setupTimeSliderLoadForTimeMap:function(a){a.on("layers-add-result",function(){var b=a.getLayersVisibleAtScale(),b=p.filter(b,function(a){if("undefined"!==typeof a.timeInfo)return a});if(0<b.length)K(b[0]);else return null})}}});
