define({
  "dailyForecastLabel": "Date de prévision : ",
  "dailyForecastDateSeparator": " au ",

  "loading": "Téléchargement en cours...",

  "regionLabel": "Région : ",
  "regionOptionNational": "National",
  "regionOptionAtlantic": "Atlantique",
  "regionOptionBc": "Colombie-Britannique",
  "regionOptionOnqc": "Ontario et Québec",
  "regionOptionPrairies": "Prairies",

  "variableLabel": "Variable météorologique : ",
  "variableOptionTemp": "Température",
  "variableOptionPrecip": "Précipitations",
  "variableOptionHeat": "Chaleur",
  "variableOptionWind": "Vent",

  "forecastPeriodLabel": "Période de prévisions : ",
  "forecastPeriodOptionWeek1": "Semaine 1",
  "forecastPeriodOptionWeek2": "Semaine 2",
  "forecastPeriodOptionWeek3": "Semaine 3",
  "forecastPeriodOptionWeek4": "Semaine 4",
  "forecastPeriod2Weeks": "2 semaines",

  "indexLabel": "Indice : ",
  "probabilityLabel": "Probabilité de : ",

  "indexTitlePrefix": "Cartes index : ",
  "probabilityTitlePrefix": "Probabilité de ",
  "probabilityTitlePrefixApos": "Probabilité d'",

  "legendTextAltTitle": "Déscription - Légende",
  "legendIndexDescription": "Les superpositions de couleurs sur cette carte symbolisent les données de prévision relatives à ${content} à partir de ${range}",
  "legendIndexDescriptionContentTemp": "le nombre de jours",
  "legendIndexDescriptionRangeTemp": "un à sept",
  "legendProbabilityDescription": "Les superpositions de couleurs sur cette carte symbolisent la probabilité que ${probability} passe de moins de trente pour cent à cent pour cent",
  "legendProbabilityDescriptionTemp": "occurrence",

  "downloadTitle": "Liens de téléchargement des cartes ci-dessus : ",
  "downloadIndexNational": "Cartes index pour l'ensemble du Canada",
  "downloadIndexAtlantic": "Cartes index pour la région de l'Atlantique",
  "downloadIndexBc": "Cartes index pour la région de la Colombie-Britannique",
  "downloadIndexOnqc": "Cartes index pour la région de l'Ontario et du Québec",
  "downloadIndexPrairies": "Cartes index pour la région des Prairies",
  "downloadProbNational": "Cartes de probabilités pour l'ensemble du Canada",
  "downloadProbAtlantic": "Cartes de probabilités pour la région de l'Atlantique",
  "downloadProbBc": "Cartes de probabilités pour la région de la Colombie-Britannique",
  "downloadProbOnqc": "Cartes de probabilités pour la région de l'Ontario et du Québec",
  "downloadProbPrairies": "Cartes de probabilités pour la région des Prairies",
  "downloadFormat": "PDF",
  "downloadSize": " ~2MB",
  "temp": "temperature",
  "precip": "precipitations",
  "heat": "chaleur",
  "wind": "vent",

  "pd": "Précipitations quotidiennes maximales",
  "p1d2_prob": "Précipitations quotidiennes supérieures à 2 mm",
  "p1d10_prob": "Précipitations quotidiennes supérieures à 10 mm",
  "p1d25_prob": "Précipitations quotidiennes supérieures à 25 mm",
  "pw": "Précipitations totales",
  "pweek25_prob": "Précipitations totales supérieures à 25 mm",
  "pweek50_prob": "Précipitations totales supérieures à 50 mm",
  "pweek100_prob": "Précipitations totales supérieures à 100 mm",
  "p10d": "Précipitations maximales sur 10 jours",
  "p10d_prob10": "Précipitations sur 10 jours supérieures à 10 mm",
  "p10d_prob100": "Précipitations sur 10 jours supérieures à 100 mm",
  "p10d_prob150": "Précipitations sur 10 jours supérieures à 150 mm",

  "ffd_warm": "Jours sans gel pour les cultures de saison chaude (> 0 °C)",
  "ffd_warm_prob": "Gel pour les cultures de saison chaude (> 0 °C)",
  "ffd_cool": "Jours sans gel pour les cultures de saison fraîche et d’hiver (> -2 °C)",
  "ffd_cool_prob": "Gel pour les cultures de saison fraîche et d’hiver (> -2 °C)",
  "dcw_warm": "Jours de vague de fraîcheur pour les cultures de saison chaude (< 10 °C)",
  "dcw_warm_prob": "Jours de vague de fraîcheur pour les cultures de saison chaude (< 10 °C)",
  "dcw_cool": "Jours de vague de fraîcheur pour les cultures de saison fraîche et d’hiver (< 5 °C)",
  "dcw_cool_prob": "Jours de vague de fraîcheur pour les cultures de saison fraîche et d’hiver (< 5 °C)",
  "dhw_warm": "Jours de vague de chaleur pour les cultures de saison chaude (> 35 °C)",
  "dhw_warm_prob": "Jours de vague de chaleur pour les cultures de saison chaude (> 35 °C)",
  "dhw_cool": "Jours de vague de chaleur pour les cultures de saison fraîche (> 30 °C)",
  "dhw_cool_prob": "Jours de vague de chaleur pour les cultures de saison fraîche (> 30 °C)",
  "ifd_grow": "Jours de gel hivernal (cultures ligneuses ou herbacées) durant la saison de croissance (< ­-2 °C)",
  "ifd_grow_prob": "Jours de gel hivernal (cultures ligneuses ou herbacées) durant la saison de croissance (< -­2 °C)",
  "ifd_herb_dorm": "Jours de gel hivernal (cultures herbacées) en période de dormance (< -15 °C)",
  "ifd_herb_dorm_prob": "Jours de gel hivernal (cultures herbacées) en période de dormance (< ­-15 °C)",
  "ifd_wood_dorm": "Jours de gel hivernal (cultures ligneuses) en période de dormance (< -30 °C)",
  "ifd_wood_dorm_prob": "Jours de gel hivernal (cultures ligneuses) en période de dormance (< -30 °C) ",
  "ifd_herb_nogrow": "Jours de gel hivernal (cultures herbacées) en dehors de la saison de croissance (< -5 °C)",
  "ifd_herb_nogrow_prob": "Jours de gel hivernal (cultures herbacées) en dehors de la saison de croissance (< -5 °C) ",
  "ifd_wood_nogrow": "Jours de gel hivernal (cultures ligneuses) en dehors de la saison de croissance (< -10 °C)",
  "ifd_wood_nogrow_prob": "Jours de gel hivernal (cultures ligneuses) en dehors de la saison de croissance (< -10 °C)",

  "egdd_warm": "Degrés-jours de croissance effectifs pour les cultures de saison chaude",
  "egdd_warm_175prob": "Degrés-jours de croissance effectifs supérieurs à 100 pour les cultures de saison chaude",
  "egdd_warm_100prob": "Degrés-jours de croissance effectifs supérieurs à 175 pour les cultures de saison chaude",
  "egdd_warm_250prob": "Degrés-jours de croissance effectifs supérieurs à 250 pour les cultures de saison chaude",
  "egdd_cool": "Degrés-jours de croissance effectifs pour les cultures de saison fraîche",
  "egdd_cool_100prob": "Degrés-jours de croissance effectifs supérieurs à 100 pour les cultures de saison fraîche",
  "egdd_cool_175prob": "Degrés-jours de croissance effectifs supérieurs à 175 pour les cultures de saison fraîche",
  "egdd_cool_250prob": "Degrés-jours de croissance effectifs supérieurs à 250 pour les cultures de saison fraîche",

  "drying": "Nombre de jours de sécheresse",
  "drying_prob": "Jours de sécheresse",
  "mdws": "Vitesse maximale du vent ",
  "mdws50_prob": "Une vitesse maximale du vent supérieure à 50 km/h",
  "mdws70_prob": "Une vitesse maximale du vent supérieure à 70 km/h",
  "mdws90_prob": "Une vitesse maximale du vent supérieure à 90 km/h",
  "nswd": "Nombre de jours de vent fort",
  "nswd_prob": "Jours de vent fort",

  "legendNumberOfDays": "nombre de jours",
  "legendRange1Week": "un à sept",
  "legendRange2Weeks": "un à quatorze",
  "legendRangeWindSpeed": "moins de trente à plus de quatre-vingt-dix kilomètres à l'heure",
  "legendRangeEGDD": "de trente-cinq à plus de deux cent soixante",
  "legendAmountPrecipitation60mm": "zéro millimètre à soixante millimètres",
  "legendAmountPrecipitation120mm": "zéro millimètres à cent vingt millimètres",
  "legendAmountPrecipitation20cm": "zéro à vingt centimètres",
});