<?php

/**
 * @file
 */

use Drupal\views\ViewExecutable;
use Drupal\views\ResultRow;
use Drupal\agri_reports\AdminHelper;

/**
 * @file
 * Primary module hooks for AgriSource Reports module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 *
 */
function agri_reports_page_attachments(array &$page) {
  $current_route = \Drupal::routeMatch()->getRouteName();
  if ($current_route == 'view.publish_activity_reporting.page_1') {
    // Only load this css for the publish activity reporting view page.
    $page['#attached']['library'][] = 'agri_reports/publish-activity';
  }
  if ($current_route == 'view.publish_activity_for_meta_tags.page_1') {
    // Only load this css for the publish activity meta view page.
    $page['#attached']['library'][] = 'agri_reports/publish-activity-meta';
  }
  if ($current_route == 'view.publish_activity_new_pages.page_1') {
    // Only load this css for the publish activity new view page.
    $page['#attached']['library'][] = 'agri_reports/publish-activity-new';
  }
}

/**
 * Implements hook_views_data_export_row_alter() for replacing current csv row values
 * with calculated values.
 */
function agri_reports_views_data_export_row_alter(&$row, ResultRow $result, ViewExecutable $view) {
  if ($view->id() == 'publish_activity_reporting') {
    $date_issued = $result->_entity->get('field_issued')->value;

    $row['field_issued'] = '';
    $values = $view->getExposedInput();
    if (!empty($values["created"]['min']) && !empty($values["created"]['max'])) {
      $date_from = $values["created"]['min'];
      $date_issued_date_only = date('Y-m-d', strtotime($date_issued));
      $date_from_date_only = date('Y-m-d', strtotime($date_from));
      if ($date_issued_date_only < $date_from_date_only) {
        $row['field_issued'] = 'Modified';
      }
      else {
        $row['field_issued'] = 'New';
      }
    }
  }
/* This view is no longer in use, replaced by James' view using direct database query.
  if ($view->id() == 'url_alias_path') {
    $path_alias = $result->path_alias_alias;
    $numchars_in_alias = strlen($path_alias);
    $row['status'] = $numchars_in_alias;

    $lang_code = $result->path_alias_langcode;
    $row['alias'] = '/' . $lang_code . $path_alias;

    $node_path = $result->path_alias_path;
    $has_node_in_path = strpos($node_path, 'node');

    if ($has_node_in_path !== FALSE) {
      $node_id = preg_replace('/[^0-9]/', '', $node_path);
      if (strlen($node_id) > 0) {
        $row['path'] = $node_id;
        $node = \Drupal::entityTypeManager()->getStorage('node')->load($node_id);
        $moderationState = $node->get('moderation_state')->getString();
        $row['id'] = $moderationState;
      }
      else {
        $row['id'] = '';
      }
    }
    else {
      $row['id'] = '';
    }
  } */
}

/**
 * Implements hook_preprocess_views_view_field() for replacing current field values
 * with calculated values.
 */
function agri_reports_preprocess_views_view_field(&$variables) {
  $view = $variables['view'];

  if ($view->id() == 'publish_activity_reporting') {
    $field = $variables['field'];
    $row = $variables['row'];
    $nid = $row->_entity->id();
    $row_entity = $row->_entity;

    if ($field->field == 'field_issued') {
      $date_issued = $row_entity->get('field_issued')->value;
      $variables['output'] = '';
      $values = $view->getExposedInput();
      if (!empty($values["created"]['min']) && !empty($values["created"]['max'])) {
        $date_from = $values["created"]['min'];
        $date_issued_date_only = date('Y-m-d', strtotime($date_issued));
        $date_from_date_only = date('Y-m-d', strtotime($date_from));
        if ($date_issued_date_only < $date_from_date_only) {
          $variables['output'] = 'Modified';
        }
        else {
          $variables['output'] = 'New';
        }
      }
    }
  }
/* This view is no longer in use, replaced by James' view using direct database query.
  if ($view->id() == 'url_alias_path') {
    $field = $variables['field'];
    $row = $variables['row'];

    if ($field->field == 'path') {
      $node_path = $row->path_alias_path;
      $has_node_in_path = strpos($node_path, 'node');
      if ($has_node_in_path !== FALSE) {
        $node_id = preg_replace('/[^0-9]/', '', $node_path);
        if (strlen($node_id) > 0) {
          $variables['output'] = $node_id;
        }
      }
    }

    if ($field->field == 'status') {
      $path_alias = $row->path_alias_alias;
      $numchars_in_alias = strlen($path_alias);
      $variables['output'] = $numchars_in_alias;
    }

    if ($field->field == 'id') {
      $node_path = $row->path_alias_path;
      $has_node_in_path = strpos($node_path, 'node');
      if ($has_node_in_path !== FALSE) {
        $node_id = preg_replace('/[^0-9]/', '', $node_path);
        if (strlen($node_id) > 0) {
          $node = \Drupal::entityTypeManager()->getStorage('node')->load($node_id);
          $moderationState = $node->get('moderation_state')->getString();
          $variables['output'] = $moderationState;
        }
        else {
          $variables['output'] = '';
        }
      }
      else {
        $variables['output'] = '';
      }
    }
  } */
}

/**
 * Implements agri_reports_views_pre_view hook.
 */
function agri_reports_views_pre_view($view, $display_id, &$args) {
  if ($view->id() == 'publish_activity_for_meta_tags' || $view->id() == 'publish_activity_new_pages') {
    $values = $view->getExposedInput();
    if (!empty($values)) {
      if (empty(trim($values["field_issued_value"]['min'])) || empty(trim($values["field_issued_value"]['max']))) {
        $values["field_issued_value"]['min'] = ' ';
        $values["field_issued_value"]['max'] = ' ';
        $view->setExposedInput($values);
      }
    }
  }

  if ($view->id() == 'publish_activity_reporting') {
    $values = $view->getExposedInput();
    if (!empty($values)) {
      if (empty(trim($values["created"]['min'])) || empty(trim($values["created"]['max']))) {
        $values["created"]['min'] = ' ';
        $values["created"]['max'] = ' ';
        $view->setExposedInput($values);
      }
    }
  }
}

/**
 * Implements hook_reports_cron().
 */
function agri_reports_cron() {
  $filedirectory = 'public://cache_warming/';
  $database = \Drupal::database();
  AdminHelper::CreateWarmingCacheJsonfile($filedirectory, $database);
}
