<?php

/**
 * @file
 * Admin functionality (mostly) custom module for aafc.
 */

use Drupal\Component\Render\FormattableMarkup;
use Drupal\node\NodeInterface;
use Drupal\Core\Render\BubbleableMetadata;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\user\Entity\User;
use Drupal\media\Entity\Media;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Entity\EntityInterface;
use Drupal\agri_admin\AgriAdminHelper;
use Drupal\agri_admin\Utils;
use Drupal\Core\Database\Database;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\file\Entity\File;
use Drupal\file\FileInterface;
use Drupal\Core\Render\Markup;
use Drupal\node\Entity\Node;

/**
 * Implements hook_preprocess_html().
 */
function agri_admin_preprocess_html(&$variables) {
  $current_path = \Drupal::service('path.current')->getPath();
  $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $current_path = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);
  $variables['current_path'] = $current_path;
  $clean_path = preg_replace('/[\W]/', '', $variables['current_path']);
  if (strlen($clean_path) > 30) {
    $clean_path = substr($clean_path, 0, 29);
  }
  if (strpos($current_path, 'node') > 0) {
    if (substr_compare($current_path, 'edit', -strlen('edit')) === 0) {
      $clean_path = 'node-edit';
    }
  }
  $variables['attributes']['class'][] = $clean_path;
  $current_user = \Drupal::currentUser();
  $roles = $current_user->getRoles();
  foreach ($roles as $rolename) {
    $variables['attributes']['class'][] = 'role-is-' . $rolename;
  }
  $path = \Drupal::request()->getpathInfo();
  $arg  = explode('/', $path);
  if ($arg[0] == $langcode && isset($arg[2])) {
    $first_two_elements = $arg[1] . '-' . $arg[2];
  }
  if ($arg[1] == $langcode && isset($arg[3])) {
    $first_two_elements = $arg[2] . '-' . $arg[3];
  }
  if (isset($first_two_elements)) {
    $variables['attributes']['class'][] = $first_two_elements;
  }

}

/**
 * Implements hook_page_attachments().
 *
 * Adds the agri-admin libraries to each page.
 */
function agri_admin_page_attachments(array &$page) {
  $user = \Drupal::currentUser();
  if ($user->hasPermission('aafc admin styles')) {
    $page['#attached']['library'][] = 'agri_admin/agri-admin';
    $current_route = \Drupal::routeMatch()->getRouteName();
    if ($current_route == 'content_moderation.admin_moderated_content' || $current_route == 'system.admin_content') {
      global $base_url;
      $page['#attached']['drupalSettings']['aafc']['base_url'] = $base_url;
      $page['#attached']['library'][] = 'agri_admin/legacy-support';
      $page['#attached']['library'][] = 'agri_admin/content-plugins-changes';
      $page['#attached']['drupalSettings']['aafc']['show_restricted_plugins_permissions'] = $user->hasPermission('aafc show restricted plugins');
    }
    if ($current_route == 'content_moderation.admin_moderated_content') {
      $page['#attached']['library'][] = 'agri_admin/agri_moderated_content';
    }
    if ($current_route == 'entity.node.edit_form' || $current_route == 'node.add') {
      $entity_id = NULL;
      $uuid = NULL;
      if (AgriAdminHelper::getSampleTopicImageUuidAndEntityId($uuid, $entity_id)) {
        $page['#attached']['drupalSettings']['campaign']['found_demo_topic'] = TRUE;
        $page['#attached']['drupalSettings']['campaign']['media_uuid'] = $uuid;
        $page['#attached']['drupalSettings']['campaign']['media_entity_id'] = $entity_id;
        $page['#attached']['drupalSettings']['special']['found_demo_topic'] = TRUE;
        $page['#attached']['drupalSettings']['special']['media_uuid'] = $uuid;
        $page['#attached']['drupalSettings']['special']['media_entity_id'] = $entity_id;
      }
      else {
        $page['#attached']['drupalSettings']['campaign']['found_demo_topic'] = FALSE;
        $page['#attached']['drupalSettings']['special']['found_demo_topic'] = FALSE;
      }
    }
  }
}

/**
 * Implements hook_theme().
 */
function agri_admin_theme($existing, $type, $theme, $path) {
  // Example of passing a variable to the theme (twig).
  return [
    'agri_admin' => [
      'variables' => ['test_var' => 'test value'],
    ],
  ];
}

/*variables array_keys=Array
(
[0] => view
[1] => rows
[2] => title
[3] => options
[4] => context
[5] => icon
[6] => icon_position
[7] => icon_only
[8] => theme_hook_original
[9] => attributes
[10] => title_attributes
[11] => content_attributes
[12] => title_prefix
[13] => title_suffix
[14] => db_is_active
[15] => is_admin
[16] => logged_in
[17] => user
[18] => directory
[19] => default_row_class
[20] => #cache
)*/

/**
 * Implements hook_preprocess_views_view_field().
 *
 *   For replacing current revision field values with latest pending revision field values.
 * This is so we can have themed (orange as example) pending draft rows. To complement the
 * hotpink current draft rows.
 *
 * @todo add {{ status }} to a view row (must be yes / no custom boolean not Yes / No , use lowercase in the view field custom.
 * May 14 2020: Added the implementation for customization on
 * Oct 16 2020: Added content view to be supported.
 */
function agri_admin_preprocess_views_view_field(&$variables) {
  $lang = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $view = $variables['view'];

  $hasPermission = FALSE;
  if ($variables['logged_in']) {
    $user = \Drupal::currentUser();
    $hasPermission = $user->hasPermission('aafc pending drafts');
  }
  $lang = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $otherLang = 'fr';
  if ($lang == 'fr') {
    $otherLang = 'en';
  }

  $view = $variables['view'];
  if ($hasPermission && ($view->id() == 'content' || $view->id() == 'moderated_content')) {
    $field = $variables['field'];
    $row = $variables['row'];
    $nid = $row->_entity->id();
    $vid = $row->_entity->getLoadedRevisionId();

    // This if block only for Moderated Content view.
    // Returning after this block ends since the rest of the code currently does not apply to this view.
    if ($view->id() == 'moderated_content') {
      if ($field->field == 'moderation_state') {
        $moderationState = $row->_entity->get('moderation_state')->getString();
        if ($moderationState == 'draft') {
          $node = \Drupal::entityTypeManager()->getStorage('node')->load($nid);
          if ($node->isPublished()) {
            $variables['output'] = t('pending draft');
          }
        }
      }
      return;
    }

    if ($row->_entity->isPublished() && $latestRevision = AgriAdminHelper::getLatestRevisionOnlyIfDraft($nid, $vid)) {
      if ($field->field == 'status') {
        // This is specifically for the row styling (view -> Format -> settings -> row {{ status }}.
        // title
        // body
        // field_fieldname
        // status
        // nid
        // field_title.
        $variables['output'] = strtolower($variables['output']);
        $variables['output'] = Markup::create(str_replace('yes', 'no pending-draft', $variables['output']));
      }
      elseif ($field->field == 'operations') {
        return;
      }
      elseif ($field->field == 'moderation_state_1') {
        // This is specifically for the row styling (view -> Format -> settings -> row {{ moderation_state_1 }}.
        // Do nothing, for styling purposes, because archived should have another color see css/scss.
        return;
      }
      elseif ($view->id() == 'content' && $field->field == 'moderation_state') {
        $variables['output'] = $variables['output'] . ' + ' . t('pending draft');
        return;
      }
      elseif ($view->id() == 'content' && $field->field == 'name') {
        // This field needs special treatment.
        // @todo Lakshman will probably notice this, will have to replace content author with revision author.
        $user = $latestRevision->getRevisionUser();
        $render_array = ['#markup' => "<a href=\"/" . $lang . "/user/" . $user->id() . "\">" . $user->getAccountName() . "</a>"];
        $variables['output'] = Utils::render($render_array);
        return;
      }
      elseif ($field->field == 'node_bulk_form') {
        // There is no fieldable field called 'node_bulk_form' this is a vbo field, so skip it.
        return;
      }
      elseif ($field->field == 'nothing') {
        // There is no fieldable field called 'nothing' this is a views field, so skip it.
        return;
      }
      elseif ($field->field == 'machine_name') {
        // There is no fieldable field called 'machine_name', so skip it.
        return;
      }
      elseif ($field->field == 'edit_node') {
        // There is no fieldable field called 'edit_node', so skip it.
        return;
      }
      elseif ($field->field == 'delete_node') {
        // There is no fieldable field called 'delete_node', so skip it.
        return;
      }
      elseif ($field->field == 'nid') {
        // There is no fieldable field called 'nid', so skip it.
        return;
      }
      elseif ($field->field == 'tid') {
        // There is no fieldable field called 'tid', so skip it.
        return;
      }
      else {
        $valueCurrent = '';
        if ($lang == 'fr') {
          $valueCurrent = $row->_entity->getTranslation($lang)->get($field->field)->value;
        }
        else {
          $valueCurrent = $row->_entity->get($field->field)->value;
        }
        // Already in current language.
        $valuePending = $latestRevision->get($field->field)->value;
        // Replace characters in the field output.
        $variables['output'] = Markup::create(str_replace($valueCurrent, $valuePending, $variables['output']));
        if ($view->id() != 'content' && ($field->field == 'title' || $field->field == 'field_title')) {
          $alias = \Drupal::service('path_alias.manager')->getAliasByPath('/node/' . $nid);
          $urlPathToLatest = '/node/' . $nid . '/latest';
          // Replace path to node in the field output.
          $variables['output'] = Markup::create(str_replace($alias, $urlPathToLatest, $variables['output']));
        }
        elseif ($view->id() == 'content' && ($field->field == 'title' || $field->field == 'field_title')) {
          $alias = \Drupal::service('path_alias.manager')->getAliasByPath('/node/' . $nid);
          $urlPathToLatest = "/$lang/node/$nid/latest";
          // Replace path to node in the field output.
          $variables['output'] = Markup::create($variables['output'] . ' <a href="' . $urlPathToLatest . '"><b>( ' . t('Pending Draft') . ' )</b></a>');
        }
      }
    }
  }

  if ($view->id() == 'moderated_content' || $view->id() == 'content') {
    $field = $variables['field'];
    if ($field->field == 'nid' || $field->field == 'id') {
      $row = $variables['row'];
      $nid = $row->_entity->id();
      // Retrieves a \Drupal\Core\Database\Connection which is a PDO instance.
      // NORMALLY DO NOT USE THIS, use \Drupal::database() instead.
      // Only doing this here because of dcr_id for altered table (not a Drupal column).
      $connection = Database::getConnection();
      $dcr_id_column_exists = $connection->schema()->fieldExists('node', 'dcr_id');
      if (!$dcr_id_column_exists) {
        return;
      }
      // Retrieves a PDOStatement object
      // http://php.net/manual/en/pdo.prepare.php
      $sth = $connection->select('node', 'n')
        ->fields('n', ['dcr_id'])
        ->condition('n.nid', $variables['output'], '=');

      // Execute the statement.
      $data = $sth->execute();

      // Get only one result.
      $result = $data->fetch();
      $value = $result->dcr_id;
      if (property_exists($result, 'dcr_id') && isset($result->dcr_id)) {
        $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
        if ($langcode == 'en') {
          $variables['output'] = Markup::create("<span class='nid'>" . $variables['output'] . "</span><span class='legacy-dcr-id'>$value</span>" .
          '<span class="fa fa-clipboard" style="margin-left: 10px" title="Copy dcr_id"></span>');
        }
        else {
          $variables['output'] = Markup::create("<span class='nid'>" . $variables['output'] . "</span><span class='legacy-dcr-id'>$value</span>" .
          '<span class="fa fa-clipboard" style="margin-left: 10px" title="Copier le dcr_id"></span>');
        }
      }
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function agri_admin_node_insert(EntityInterface $entity) {
  $entity_id = $entity->id();

  $action = 'insert';
  AgriAdminHelper::addToLog(__function__);
  drupal_register_shutdown_function('_helper_update_process', $action, $entity_id, $entity->bundle());
  drupal_register_shutdown_function('_helper_locking_content', $action, $entity_id, $entity->bundle(), $entity);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function agri_admin_node_update(EntityInterface $entity) {
  $entity_id = $entity->id();
  $action = 'update';
  // AgriAdminHelper::addToLog(print_r($DEBUG_THIS, TRUE), TRUE);.
  global $import_override;
  if (!isset($import_override) || $import_override == FALSE) {
    drupal_register_shutdown_function('_helper_update_process', $action, $entity_id, $entity->bundle());
    drupal_register_shutdown_function('_helper_locking_content', $action, $entity_id, $entity->bundle(), $entity);
  }
}

/**
 * Implements hook_entity_type_predelete().
 */
function agri_admin_media_predelete(EntityInterface $entity) {
  if (strpos($entity->getName(), 'pecial_title520x') > 0) {
    // Set error message
    // display error.
    // Prevent delete.
    $entity_type = $entity->getEntityTypeId();
    $id = $entity->id();
    $response = new RedirectResponse(Url::fromUri('internal:/' . $entity_type . '/' . $id . '/delete')->toString());
    \Drupal::messenger()->addMessage(t('Agri Admin prevented you from deleting "%title" entity_id %id because this file is reserved for the special title functionality.', [
      '%id' => $entity->id(),
      '%title' => $entity->getName(),
    ]), 'warning', TRUE);
    $response->send();
    exit;
  }
}

/**
 * Implements hook_form_alter().
 */
function agri_admin_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ((strpos($form_id, 'media') !== FALSE && strpos($form_id, 'edit_form') !== FALSE) ||
      (strpos($form_id, 'media') !== FALSE && strpos($form_id, 'add') !== FALSE)
  ) {
    // Get rid of ugly text to the right of the dropdown list on the media field.
    if (isset($form['field_aafc_category'])) {
      foreach ($form['field_aafc_category']['widget'] as $key => $value) {
        if ($key == '#options') {
          foreach ($form['field_aafc_category']['widget'][$key] as $i_key => $i_value) {
            $category_term = $i_value;
            $strpos_bad_text_idx = stripos($i_value, '(Taxonomy term', 1);
            $strpos_bad_text_fr_idx = stripos($i_value, '(Terme de tax', 1);
            if ($strpos_bad_text_idx > 1) {
              // Cleanup for English.
              $form['field_aafc_category']['widget'][$key][$i_key] = substr($i_value, 0, $strpos_bad_text_idx);
            }
            if ($strpos_bad_text_fr_idx > 1) {
              // Nettoyage pour le français.
              $form['field_aafc_category']['widget'][$key][$i_key] = substr($i_value, 0, $strpos_bad_text_fr_idx);
            }
          }
        }
      }
    }
  }
  if ((strpos($form_id, 'media') !== FALSE && strpos($form_id, 'edit_form') !== FALSE) ||
      (strpos($form_id, 'media') !== FALSE && strpos($form_id, 'delete') !== FALSE)
  ) {
    $path = \Drupal::request()->getpathInfo();
    $arg = explode('/', $path);
    $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
    $index_arg = 0;
    $idx = 0;
    foreach ($arg as $segment) {
      if (is_numeric($segment) && !is_bool($segment)) {
        $index_arg = $idx;
      }
      $idx++;
    }
    if (isset($arg[$index_arg]) && is_numeric($arg[$index_arg])) {
      $mid = $arg[$index_arg];
      $fid = $arg[$index_arg];
    }
    else {
      // This should never happen.
      return;
    }

    if (strpos($form_id, 'media') !== FALSE || strpos($form_id, 'delete')) {
      $media = Media::load($mid);
      $show_button = TRUE;
      if (strpos($media->getName(), 'pecial_title520x') >= 1) {
        $show_button = FALSE;
      }
      if (!$show_button) {
        $msg_type = t('Do not edit or delete this file.');
        $message_ok = t('Special title verification check status, do not edit or delete this file, it is reserved for the special title functionality.');
        $markup = <<<EOT
<div role="contentinfo" aria-labelledby="message-status-title" class="messages-list__item messages messages--warning">
  <div class="messages__header">
    <h2 id="message-status-title" class="messages__title">
      $msg_type
    </h2>
  </div>
  <div class="messages__content">
    $message_ok
  </div>
</div>
EOT;
        $form['description']['#markup'] = $markup;
        // $form['actions']['submit']['#access'] = $show_button ? TRUE : FALSE;
        $form['actions']['submit']['#attributes'] = ['disabled' => $show_button ? 'enabled' : 'disabled'];
      }
    }
  }

}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function agri_admin_node_presave(EntityInterface $entity) {
  // Exit early if possible.
  if ($entity->getEntityTypeId() != 'node') {
    return;
  }
  // Custom code goes here:
  global $import_override;

  $entity_id = $entity->id();
  // Set Authored by to current user if role is creator except during Peer Review.
  $current_author_id = $entity->getOwnerId();
  $current_user = \Drupal::currentUser();
  $current_user_id = $current_user->id();
  $roles = $current_user->getRoles();
  $authored_on = $entity->getCreatedTime();
  $content_type = $entity->bundle();

  if ($content_type == 'page' || $content_type == 'landing_page') {
    $changed_time = $entity->getChangedTime();
    $date_issued = $entity->get('field_issued')->getString();
    $date_modified = $entity->get('field_modified')->getString();
    $moderation_state = $entity->moderation_state->value;
    $created_by = $entity->get('field_created_by')->getString();
    // AgriAdminHelper::addToLog(print_r('Current: '.$current_user, TRUE), TRUE);.
    if (empty($created_by)) {
      if ($entity->isNew()) {
        $entity->set('field_created_by', $current_user->getAccountName());
      }
      else {
        $admin_username = User::load(1)->getAccountName();
        $entity->set('field_created_by', $admin_username);
      }
    }

    $peer_review_status = '';
    if ($content_type == 'page' || $content_type == 'landing_page') {
      $update_date_modified_str = $entity->get('field_update_date_modified')->getString();
      $peer_review_status = $entity->get('field_peer_review')->getString();
      if ($moderation_state == 'published' || $moderation_state == 'archived') {
        $entity->set('field_peer_review', '');
      }
    }
    else {
      // Just making not zero and different from 1 for debug ease.
      $update_date_modified_str = '2';
    }

    if ($moderation_state == 'published') {
      $dt = new DateTime();
      if (empty($date_issued)) {
        $entity->set('field_issued', $dt->format('Y-m-d'));
      }

      if ($update_date_modified_str == '0' || (isset($import_override) && $import_override)) {
        $langcode = AgriAdminHelper::getLang();
        // The changed field is translateable, must set value twice, otherwise unexpected issues during import.
        if ($entity->get('changed')->getFieldDefinition()->isTranslatable()) {
          // For some reason we enabled translation for changed field on this.
          if ($langcode == 'en') {
            if ($entity->hasTranslation('fr')) {
              $entity->getTranslation('fr')->set('changed', strtotime($date_modified));
            }
            if ($entity->hasTranslation('en')) {
              $entity->getTranslation('en')->set('changed', strtotime($date_modified));
            }
          }
          else {
            if ($entity->hasTranslation('en')) {
              $entity->getTranslation('en')->set('changed', strtotime($date_modified));
            }
            if ($entity->hasTranslation('fr')) {
              $entity->getTranslation('fr')->set('changed', strtotime($date_modified));
            }
          }
        }
        else {
          // If translation of this field is disabled make sure still works.
          $entity->set('changed', strtotime($date_modified));
        }
      }
      else {
        $entity->set('field_modified', $dt->format('Y-m-d'));
      }
    }

    // AgriAdminHelper::addToLog('update_date_modified_str: ' . $update_date_modified_str, TRUE);.
  }

  foreach ($roles as $value) {
    $role = $value;
    if (($role == 'creator' &&  empty($peer_review_status))) {
      // AgriAdminHelper::addToLog('presave called for ' . $entity->language()->getId() . ' ' . $entity->id(), TRUE);.
      $langcode = $entity->language()->getId();
      if ($langcode == 'en') {
        $entity->getTranslation('fr')->setOwnerId($current_user_id);
      }
      else {
        $entity->getTranslation('en')->setOwnerId($current_user_id);
      }
      $entity->setOwnerId($current_user_id);
      $entity->set('created', time());
    }
  }
}

/**
 * Custom helper function for content locking.
 */
function _helper_locking_content($action, $entity_id, $bundle, $entity_obj = NULL) {
  global $import_override;
  $content_type = $entity_obj->bundle();
  if (!isset($import_override) || $import_override == FALSE) {
    if ($action == 'insert' || $action == 'update') {
      $current_user = \Drupal::currentUser();
      $current_user_id = $current_user->id();
      if ($action == 'update') {
        // AgriAdminHelper::getLatestRevision($entity_id, $vid);.
        $latest = $entity_obj;
      }
      if ($action == 'insert') {
        $latest = $entity_obj;
      }
      $current_author_id = $latest->getOwnerId();
      if (!isset($current_author_id)) {
        $current_author_id = $current_user_id;
      }

      $lock_service = \Drupal::service('content_lock');
      $is_creator = FALSE;
      $is_master = FALSE;
      $is_reviewer = FALSE;
      $roles = $current_user->getRoles();
      foreach ($roles as $value) {
        $role = $value;
        if ($role == 'creator'/*DISABLE FOR TESTING*/) {
          $is_creator = TRUE;
          $state = $latest->get('moderation_state')->getString();
          $peer_review_status = '';
          if ($content_type == 'page' || $content_type == 'landing_page') {
            $peer_review_status = $latest->get('field_peer_review')->getString();
          }
          if ($state == 'draft' && empty($peer_review_status)) {
            $lock_service->locking($entity_id, $latest->language()->getId(), 'edit', $current_user_id, $latest->getEntityTypeId());
            // Finished processing.
            return;
          }
          else {
            $lock_service->release($entity_id, $latest->language()->getId(), 'edit', $current_author_id, $latest->getEntityTypeId());
          }
        }
        if ($role == 'reviewer' && $state == 'with_reviewer') {
          $is_reviewer = TRUE;
          // Persist the lock for the reviewer.
          $lock_service->locking($entity_id, $latest->language()->getId(), 'edit', $current_user_id, $latest->getEntityTypeId());
          // Finished processing.
          return;
        }
      }
      // $original_state = $entity_obj->getOriginal('moderation_state')->getString();
      $state = $latest->get('moderation_state')->getString();
      if ($state == 'review_by_reviewer' && !$is_creator && !is_null($entity_obj)) {
        // @todo for Deepani - Call a function that sends an email to the reviewer role.
        // @todo Check the content type of $latest (entity) and do a case, possibly different group email per content type.
      }
      if ($state == 'author_reviewing' && !$is_creator && !is_null($entity_obj)) {
        // Reviewer is rejecting, sends back to author_reviewing, re-assigns the lock to the $current_author_id.
        $lock_service->locking($entity_id, $latest->language()->getId(), 'edit', $current_author_id, $latest->getEntityTypeId());
        // @todo for Deepani - Call a function that sends an email to $current_author_id (get email address) and send email.
      }
      elseif (!$is_creator) {
        // Is neither reviewer, nor creator, therefore release all locks.
        $lock_service->release($entity_id, $latest->language()->getId(), 'edit', $current_user_id, $latest->getEntityTypeId());
        $lock_service->release($entity_id, $latest->language()->getId(), 'edit', $current_author_id, $latest->getEntityTypeId());
      }
    }
  }
}

/**
 * Helper function for entity updates (node updates particularly).
 */
function _helper_update_process($action, $entity_id, $bundle) {
  global $import_override;
  if (!isset($import_override) || $import_override == FALSE) {
    AgriAdminHelper::addToLog('_helper_update_process action=' . $action . ' : ' . $entity_id . ' : ' . $bundle);
    $menu_link_ids = [];
    $menu_link_ids = AgriAdminHelper::postCreateOrUpdateAutoTranslate($action, $entity_id, $bundle);
    // AgriAdminHelper::postUpdateProcess($action, $entity_id, $bundle);.
    if ($bundle == 'page') {
      // AgriAdminHelper::disableMenuLink(NULL, $entity_id, 'sidebar', TRUE);.
      AgriAdminHelper::disableMenuLink(NULL, $entity_id, 'sidebar', TRUE);
    }

    if (\Drupal::currentUser()->isAuthenticated()) {
      $content_type = $bundle;
      $entity = \Drupal::entityTypeManager()->getStorage('node')->load($entity_id);
      if ($content_type == 'page') {
        if (isset($entity->moderation_state)) {
          $moderation_state = $entity->moderation_state->value;
          if ($moderation_state == 'archived') {
            if (AgriAdminHelper::menuLinkAction($entity_id, 'sidebar', 'delete')) {
              AgriAdminHelper::addMessage(t('Menu link deleted for "%type" now "archived" node id: %id', [
                '%id' => $entity_id,
                '%type' => 'Internal page',
              ]
                )
              );
            }
            else {
              AgriAdminHelper::addMessage(t('Menu link not found for now "archived" %type node id: %id', [
                '%id' => $entity_id,
                '%type' => 'page',
              ])
              );
            }
          }
        }
      }
      if ($content_type == 'landing_page') {
        if (isset($entity->moderation_state)) {
          $moderation_state = $entity->moderation_state->value;
          if ($moderation_state == 'archived') {
            if (AgriAdminHelper::menuLinkAction($entity_id, 'sidebar', 'disable')) {
              AgriAdminHelper::addMessage(t('Menu link disabled for "%type" now "archived" node id: %id', [
                '%id' => $entity_id,
                '%type' => 'Landing page',
              ]
                )
              );
            }
            else {
              AgriAdminHelper::addMessage(t('Menu link not found for now "archived" %type node id: %id', [
                '%id' => $entity_id,
                '%type' => 'Landing page',
              ])
              );
            }
          }
          if ($moderation_state != 'archived' && AgriAdminHelper::menuLinkExists($entity_id, 'sidebar')) {
            $result_code = AgriAdminHelper::menuLinkAction($entity_id, 'sidebar', 'enable');
          }
        }
      }
    }
  }
}

/**
 * Submit handler for the agri_admin node form customizations.
 */
function agri_admin_form_page_submit(array $form, FormStateInterface $form_state) {
  // $current_user = \Drupal::currentUser();
  $entity = $form_state->getFormObject()->getEntity();
  $moderation_state = $entity->moderation_state->value;
  if ($moderation_state == 'delete') {
    $language = \Drupal::languageManager()->getCurrentLanguage();
    $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
    $url = Url::fromRoute('<front>', [], ['language' => $language]);
    $title = $entity->getTitle();
    $msg = t('The archived content <em class="placeholder"> %title</em> has been deleted.', ['%title' => $title]);
    $nid = $entity->id();
    $node = Node::load($nid);
    if (isset($node)) {
      $node->delete();
      // Clearing buff message and reset deletion message.
      \Drupal::messenger()->deleteAll();
      \Drupal::messenger()->addStatus(['#markup' => $msg]);
      $form_state->setRedirectUrl($url);
    }
  }
}

/**
 * Implements hook_form_node_form_alter().
 */
function agri_admin_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $entity = $form_state->getFormObject()->getEntity();
  $content_type = $entity->bundle();
  if ($content_type == 'page' || $content_type == 'landing_page') {
    $form['field_issued']['widget'][0]['#disabled'] = TRUE;
    $form['field_modified']['widget'][0]['#disabled'] = TRUE;
    $form['field_created_by']['widget'][0]['#disabled'] = TRUE;
    $form['field_dc_date_created']['widget'][0]['#disabled'] = TRUE;
    // For page and landing page edit/add css.
    $form['#attached']['library'][] = 'agri_admin/page';
    // Add validation functionality to prevent the broken links or misused linkit before the page is published.
    $form['#validate'][] = 'agri_admin_publishpage_referredlinks_validation';
    // For page and landing page edit/add js.
    $form['#attached']['library'][] = 'agri_admin/campaign';
    $form['#attached']['library'][] = 'agri_admin/special';
    // Attached agri_admin_form_page_submit event handler to page, landing page
    $moderation_state = $entity->moderation_state->value;
    if ($moderation_state == 'archived') {
      $form['actions']['submit']['#submit'][] = 'agri_admin_form_page_submit';
    }

    // AgriAdminHelper::addToLog($debug_message, TRUE);
    // Copying fields to label:
    if (isset($form['field_dc_date_created']['widget'][0])) {
      $date_created_date = $form['field_dc_date_created']['widget'][0]['value']['#default_value'];
      if (is_object($date_created_date)) {
        $form['field_dc_date_created']['widget'][0]['value']['#title'] = t('dc.date.created: @date_created', [
          '@date_created' => $date_created_date->format('Y-m-d'),
        ]
        );
      }
      else {
        $form['field_dc_date_created']['widget'][0]['value']['#title'] = t('dc.date.created: @date_created', [
          '@date_created' => '',
        ]
        );
      }
      $form['field_dc_date_created']['#attributes']['class'] = 'hidden-input-box';
    }

    if (isset($form['field_created_by']['widget'][0])) {
      $created_by = $form['field_created_by']['widget'][0]['value']['#default_value'];
      if (!empty($created_by)) {
        $form['field_created_by']['widget'][0]['value']['#title'] = t('Created by: @created_by', [
          '@created_by' => $created_by,
        ]
        );
      }
      else {
        $form['field_created_by']['widget'][0]['value']['#title'] = t('Created by:');
      }
      $form['field_created_by']['#attributes']['class'] = 'hidden-input-box';
    }

    if (isset($form['field_issued']['widget'][0])) {
      $date_issued = $form['field_issued']['widget'][0]['value']['#default_value'];
      if (is_object($date_issued)) {
        $form['field_issued']['widget'][0]['value']['#title'] = t('dcterms:issued @date_issued', [
          '@date_issued' => $date_issued->format('Y-m-d'),
        ]
        );
      }
      else {
        $form['field_issued']['widget'][0]['value']['#title'] = t('dcterms:issued:');
      }
      $form['field_issued']['#attributes']['class'] = 'hidden-input-box';
    }

    if (isset($form['field_modified']['widget'][0])) {
      $date_modified = $form['field_modified']['widget'][0]['value']['#default_value'];
      if (is_object($date_modified)) {
        $form['field_modified']['widget'][0]['value']['#title'] = t('dcterms:modified: @date_modified', [
          '@date_modified' => $date_modified->format('Y-m-d'),
        ]
        );
      }
      else {
        $form['field_modified']['widget'][0]['value']['#title'] = t('dcterms:modified:');
      }
      $form['field_modified']['#attributes']['class'] = 'hidden-input-box';
    }

    if ($content_type == 'page' || $content_type == 'landing_page') {
      $moderation_state = $entity->moderation_state->value;
      $peer_review_status = $entity->get('field_peer_review')->getString();

      if ($entity->isNew()) {
        $form['field_peer_review']['#disabled'] = TRUE;
      }
      elseif ($moderation_state == 'published' || $moderation_state == 'archived') {
        $form['field_peer_review']['#disabled'] = TRUE;
        $form['field_tracking_number']['widget'][0]['value']['#default_value'] = '';
      }
      elseif ($moderation_state == 'draft' &&  empty($peer_review_status)) {
        // Do not enable peer reviewed.
        $form['field_peer_review']['widget']['#options_attributes']['peer_reviewed']['disabled'] = 'disabled';
      }
    } //End handle Peer_Review for page/landing_page only.
  }// End page/landing_page.

  $current_user = \Drupal::currentUser();
  $roles = $current_user->getRoles();
  foreach ($roles as $role) {
    if ($role == 'ia') {
      foreach ($form as $key => $value) {
        if (isset($value)) {
          if (strpos($key, '_meta') == FALSE) {
            if (strpos($key, 'field_') !== FALSE) {
              $form[$key]['#disabled'] = TRUE;
            }
          }
        }
      }
      $form['title']['#disabled'] = TRUE;
      $form['layout_selection']['#disabled'] = TRUE;
      $form['field_description']['#disabled'] = FALSE;
      $form['field_keywords']['#disabled'] = FALSE;
      $form['field_subject']['#disabled'] = FALSE;
    }
  }
}

/**
 * Implements custom validation for checking three cases when the user publishes the page.
 *
 * Case #1: The link contains token.
 * Case #2: The link refers unpublished node.
 * Case #3: The link uses absolute URL path.
 */
function agri_admin_publishpage_referredlinks_validation(&$form, &$form_state) {
  $langcode = AgriAdminHelper::getLang();
  // Default language - body field
  // Since it is in validation stage, i have to get the body value from $form variable instead of node entity.
  $formbodydefault = $form['body']['widget'][0]['value']['#value'];
  $formbody2 = "";
  if ($langcode == 'en') {
    $formbody2 = $form['body']['fr']['widget'][0]['value']['#value'];
  }
  else {
    $formbody2 = $form['body']['en']['widget'][0]['value']['#value'];
  }
  $entity = $form_state->getFormObject()->getEntity();
  $nType = $entity->bundle();

  // Get the moderation state value from form values.
  $formvalues = $form_state->getValues();
  $tmp = array_pop($formvalues['moderation_state']);
  $node_mstate = array_pop($tmp);
  if (($nType == 'page' || $nType == 'landing_page') && ($node_mstate == 'published')) {
    $foundtokenhref = FALSE;
    agri_admin_checkurltoken($formbodydefault, $foundtokenhref, $langcode);
    agri_admin_checkurltoken($formbody2, $foundtokenhref, $langcode);

    // Check unpublished node.
    $foundunpublishingnode = FALSE;
    agri_admin_checkpagepublished($formbodydefault, $foundunpublishingnode, $langcode);
    agri_admin_checkpagepublished($formbody2, $foundunpublishingnode, $langcode);

    // Check absolute URL.
    $foundabsoluteurl = FALSE;
    agri_admin_checkabsoluteurl($formbodydefault, $foundabsoluteurl, $langcode);
    agri_admin_checkabsoluteurl($formbody2, $foundabsoluteurl, $langcode);

    // Prevent the user to publish the page.
    if ($foundtokenhref || $foundunpublishingnode || $foundabsoluteurl) {
      $form_state->setRebuild();
    }
  }
}

/**
 * Implements check if the href contains token before the user publishes the current page.
 */
function agri_admin_checkurltoken($formbody, &$foundtokenhref = FALSE, $langcode = 'en') {
  // Token string pattern.
  $tokenmsg = '';
  if ($langcode == 'en') {
    $tokenmsg = '<p style="color:#e0ac00; font-size:16px;"><strong>Please remove any links to Preview/Draft pages (pages whose URL contains "auHash").</strong></p>';
  }
  else {
    $tokenmsg = '<p style="color:#e0ac00; font-size:16px;"><strong>Veuillez supprimer tous les liens vers les pages d\'aperçu/de projet (pages dont l\'URL contient "auHash").</strong></p>';
  }
  $tokenmsgarray = [];
  Utils::checkUrlToken($formbody, $foundtokenhref, $tokenmsgarray);
  if ($foundtokenhref) {
    $warning = Markup::create($tokenmsg);
    \Drupal::messenger()->addWarning($warning);
  }
  return $foundtokenhref;
}

/**
 * Implements check if the href page is published before the user publishes the current page.
 */
function agri_admin_checkpagepublished($formbody, &$foundunpublishingnode = FALSE, $langcode = 'en') {
  $unpublishingnodemsg = '';
  if ($langcode == 'en') {
    $unpublishingnodemsg = '<p style="color:#e0ac00; font-size:16px;"><strong>Please publish the identified pages first and then publish the current one.</strong></p>';
  }
  else {
    $unpublishingnodemsg = '<p style="color:#e0ac00; font-size:16px;"><strong>Veuillez d\'abord publier les pages identifiées, puis publier la page actuelle.</strong></p>';
  }
  $regex_mediaobj = "/data-entity-type=\"node\" data-entity-uuid=\"([a-z]|[0-9]){8}-(([0-9]|[a-z]){4}-){3}([0-9]|[a-z]){12}\"/";
  $regex_uuid = "/([a-z]|[0-9]){8}-(([0-9]|[a-z]){4}-){3}([0-9]|[a-z]){12}/";
  $publishpagemsgarray = [];
  Utils::checkPagePublished($formbody, $foundunpublishingnode, $publishpagemsgarray);
  if ($foundunpublishingnode) {
    $warning = Markup::create($unpublishingnodemsg);
    \Drupal::messenger()->addWarning($warning);
    foreach ($publishpagemsgarray as $msg) {
      $warning = Markup::create($msg);
      \Drupal::messenger()->addWarning($warning);
    }
  }
  return $foundunpublishingnode;
}

/**
 * Implements check if the href url is absolute URL before the user publishes the current page.
 */
function agri_admin_checkabsoluteurl($formbody, &$foundabsoluteurl = FALSE, $langcode = 'en') {
  $absoluteurlmsg = '';
  if ($langcode == 'en') {
    $absoluteurlmsg = '<p style="color:#e0ac00; font-size:16px;"><strong>Please use Linkit to complete the reference.</strong></p>';
  }
  else {
    $absoluteurlmsg = '<p style="color:#e0ac00; font-size:16px;"><strong>Veuillez utiliser Linkit pour compléter la référence.</strong></p>';
  }
  $absoluteurlmsgarray = [];
  Utils::checkAbsoluteUrl($formbody, $foundabsoluteurl, $absoluteurlmsgarray);
  if ($foundabsoluteurl) {
    $warning = Markup::create($absoluteurlmsg);
    \Drupal::messenger()->addWarning($warning);
    foreach ($absoluteurlmsgarray as $msg) {
      $warning = Markup::create($msg);
      \Drupal::messenger()->addWarning($warning);
    }
  }

  return $foundabsoluteurl;
}

/**
 * Implements hook_system_breadcrumb_alter().
 *
 * For /node/add/ page.
 */
function agri_admin_system_breadcrumb_alter(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match, array $context) {
  $current_path = \Drupal::service('path.current')->getPath();
  $result = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);
  $previousUrl = \Drupal::request()->server->get('HTTP_REFERER');
  $node_preview = \Drupal::routeMatch()->getParameter('node_preview');
  $node = \Drupal::routeMatch()->getParameter('node');
  $nid = 0;
  $nType = '';
  if ($node_preview) {
    $nType = $node_preview->getType();
  }
  if (isset($node) && !is_string($node) && is_object($node) && method_exists($node, 'getType')) {
    $nType = $node->getType();
    $nid = $node->id();
  }

  // Logic is for rebuilding the Breadcrumb for the preview latest vesrion and authentication user to edit the page.
  $regpath = '/\/node\/([1-9])\d*\/(latest|moderation-history|layout|delete|edit|revisions)/';
  $regpathlatest = '/\/node\/([1-9])\d*\/(latest|layout)/';
  $latest_bool = FALSE;
  if (preg_match($regpathlatest, $result)) {
    $latest_bool = TRUE;
  }
  if (preg_match($regpath, $result)) {
    $links = $breadcrumb->getlinks();
    $breadcrumb = new Breadcrumb();
    $breadcrumb->addLink($links[0]);
    // www.drupal.org/node/2876622 addCacheContexts for new breadcrumb.
    $breadcrumb->addCacheContexts(['url.path', 'languages']);
    $tmpstr = explode('/', $result);
    if (isset($tmpstr[2]) && is_numeric($tmpstr[2])) {
      $nid = $tmpstr[2];
      $langcode = AgriAdminHelper::getLang();
      $url_alias = \Drupal::service('path_alias.manager')->getAliasByPath('/node/' . $nid, $langcode);
      $aliapthArray = explode('/', $url_alias);
      if ($latest_bool) {
        // Do not add the last menu item.
        array_pop($aliapthArray);
      }
      $tmpPath = '';
      array_shift($aliapthArray);
      foreach ($aliapthArray as $nodetitle) {
        $tmpPath = $tmpPath . '/' . $nodetitle;
        $path = \Drupal::service('path_alias.manager')->getPathByAlias($tmpPath);
        $tmpnidarray = explode('/', $path);
        if (isset($tmpnidarray[2]) && is_numeric($tmpnidarray[2])) {
          $nid = $tmpnidarray[2];
          $link = \Drupal::entityTypeManager()->getStorage('node')->load($nid);
          if ($link) {
            if ($link->hasTranslation($langcode)) {
              $link = $link->getTranslation($langcode);
            }
            // Retrieve Menu title based on langcode.
            $system_uri = 'entity:node/' . $nid;
            $result = Utils::getMenuItemTitle($system_uri, $langcode);
            if (isset($result)) {
              $title = $result;
            }
            else {
              // Assign the default node title.
              $title = $link->getTitle();
            }
            $linkNew = $link->toLink($title);
            if (isset($linkNew)) {
              $breadcrumb->addLink($linkNew);
            }
          }
        }
      }
    }
  }
}

/**
 * Implements hook_preproces_breadcrumb().
 *
 * For /node/add/ page.
 */
function agri_admin_preprocess_breadcrumb(&$variables) {
  if ($variables['breadcrumb']) {
    $request = \Drupal::request();
    $route_match = \Drupal::routeMatch();
    $page_title = \Drupal::service('title_resolver')->getTitle($request, $route_match->getRouteObject());
    $current_path = \Drupal::service('path.current')->getPath();
    $result = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function agri_admin_preprocess_field_multiple_value_form(&$vars) {
  if (!\Drupal::currentUser()->isAnonymous()) {
    return;
  }
  // Anonymous only logic below.
  // Remove weight option for multivalue fields.
  if (isset($vars['table']['#tabledrag'])) {
    unset($vars['table']['#tabledrag']);
    array_pop($vars['table']['#header']);
    foreach ($vars['table']['#rows'] as &$row) {
      foreach ($row['data'] as $key => $rowrowdata) {
        if (!$rowrowdata['data']) {
          unset($row['data'][$key]);
        }
      }
    }
  }
}

/**
 * Implements hook_preprocess_fieldset_HOOK().
 */
function agri_admin_preprocess_fieldset(&$variables) {
  unset($variables['attributes']['required']);
  unset($variables['attributes']['aria-required']);
  unset($variables['attributes']['aria-invalid']);
}

/**
 * Implements hook_content_moderation_notification_mail_data_alter().
 */
function agri_admin_content_moderation_notification_mail_data_alter(EntityInterface $entity, array &$data) {
  $entitiyLang = $entity->get('langcode')->value;
  // Avoid sending two emails for the same entity (en and fr).
  // The French information will be included in the English email.
  if ($entitiyLang == 'en') {
    $currentModState = $entity->get('moderation_state')->getString();
    $nType = $entity->bundle();
    // For basic and landing page CT, default email list will be used.
    // When publishing happens and no emails will be sent when drafts are created.
    if ($currentModState == 'draft') {
      $data['to'] = [];
    }
  }
  if ($entitiyLang == 'fr') {
    $data['to'] = [];
  }
}

/**
 * Implements hook_token_info().
 */
function agri_admin_token_info() {
  $info = [];
  $info['types']['agri-admin'] = [
    'name' => t('Agri Admin Custom Token'),
    'description' => t('Custom Group to use in content moderation notification emails'),
  ];
  $info['tokens']['agri-admin']['translation-title'] = [
    'name' => t('Translation title'),
    'description' => t('A token to extract the translated node title'),
  ];
  $info['tokens']['agri-admin']['translation-url'] = [
    'name' => t('Translation url'),
    'description' => t('A token to extract the translated URL'),
  ];
  $info['tokens']['agri-admin']['title'] = [
    'name' => 'Title',
    'description' => t('A token to extract the current title for using submission form'),
  ];
  $info['tokens']['agri-admin']['url'] = [
    'name' => t('Url'),
    'description' => t('A token to extract the current URL for when using submission form'),
  ];
  $info['tokens']['agri-admin']['unpublished-url'] = [
    'name' => t('Unpublished url'),
    'description' => t('A token to extract the unpublished URL for anonymous users'),
  ];
  $info['tokens']['agri-admin']['translation-unpublished-url'] = [
    'name' => t('Translation unpublished url'),
    'description' => t('A token to extract the unpublished French URL for anonymous users'),
  ];
  $info['tokens']['agri-admin']['user-agent'] = [
    'name' => t('User agent'),
    'description' => t('A token to display the information of user agent'),
  ];
  $info['tokens']['agri-admin']['public-facing-url'] = [
    'name' => t('Public facing URL'),
    'description' => t('A token to extract the current public facing URL'),
  ];
  $info['tokens']['agri-admin']['translation-public-facing-url'] = [
    'name' => t('Translation Public facing URL'),
    'description' => t('A token to extract the current public facing URL in French'),
  ];
  return $info;
}

/**
 * Implements hook_tokens().
 */
function agri_admin_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $replacements = [];
  if ($type == 'agri-admin' && isset($data['entity']) && $data['entity'] instanceof NodeInterface) {
    $entity = $data['entity'];
    if ($entity->hasTranslation('fr')) {
      $translated_entity = $entity->getTranslation('fr');
    }
    else {
      $translated_entity = $entity;
    }
    $translated_title = $translated_entity->getTitle();
    $translated_url = $translated_entity->toLink()->toString();
    $current_title = $entity->getTitle();
    $current_url = $entity->toLink()->toString();
    $transLangID = $translated_entity->language()->getId();
    $currentLangID = \Drupal::languageManager()->getCurrentLanguage()->getId();
    $nodeID = $entity->id();

    $host = \Drupal::request()->getHost();
    $anonymous_url = str_replace("-admin", "", $host);
    
    if (stripos($host, 'www-tmp.agr.gc.ca') !== false || stripos($host, 'www-ep.agr.gc.ca') !== false || stripos($host, 'agriculture.agr.gc.ca') !== false) {
      $anonymous_url = 'agriculture.canada.ca';
    }
    
    $publicFacing_str = '<a href="https://' . $anonymous_url . '/' . $currentLangID . '/node/' . $nodeID . '">' . $current_title . '</a>';
    $publicFacing_url = Markup::create($publicFacing_str);

    $currentLang = \Drupal::languageManager()->getCurrentLanguage();
    $hashTag = AgriAdminHelper::getHashTag($entity, $currentLang);
    $path = '<a href="' . $hashTag . '">' . $current_title . '</a>';
    $unpublished_url = Markup::create($path);

    $transLang = $translated_entity->language();
    $hashTagTrans = AgriAdminHelper::getHashTag($translated_entity, $transLang);
    $transPath = '<a href="' . $hashTagTrans . '">' . $translated_title . '</a>';
    $translated_unpublished_url = Markup::create($transPath);

    $transPublicFacing_str = '<a href="https://' . $anonymous_url . '/' . $transLangID . '/node/' . $nodeID . '">' . $translated_title . '</a>';
    $translated_publicFacing_url = Markup::create($transPublicFacing_str);

    foreach ($tokens as $name => $original) {
      // Find the desired token by name.
      switch ($name) {
        case 'translation-title':
          $replacements[$original] = $translated_title;
          break;

        case 'translation-url':
          $replacements[$original] = $translated_url;
          break;

        case 'title':
          $replacements[$original] = $current_title;
          break;

        case 'url':
          $replacements[$original] = $current_url;
          break;

        case 'unpublished-url':
          $replacements[$original] = $unpublished_url;
          break;

        case 'translation-unpublished-url':
          $replacements[$original] = $translated_unpublished_url;
          break;

        case 'public-facing-url':
          $replacements[$original] = $publicFacing_url;
          break;

        case 'translation-public-facing-url':
          $replacements[$original] = $translated_publicFacing_url;
          break;
      }
    }
  }
  // Add token for webform only.
  if ($type == 'agri-admin' && !(isset($data['entity']) && $data['entity'] instanceof NodeInterface)) {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'user-agent':
          $useragent = $_SERVER['HTTP_USER_AGENT'];
          $replacements[$original] = $useragent;
          break;
      }
    }
  }
  return $replacements;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function agri_admin_form_menu_link_content_menu_link_content_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id = 'menu_link_content_menu_link_content_form') {
    // AgriAdminHelper::addToLog('form_id ' . $form_id, TRUE);.
    // For hiding disabled items adding checkbox.
    $form['#attached']['library'][] = 'agri_admin/menu-navigation-hide-disabled';
  }

  // @todo convert this logic into a contrib module, BEGIN MENU EDIT/ADD LINK OPTIMISATION HERE:
  $route_match = Utils::getRouteName();
  $current_path = \Drupal::service('path.current')->getPath();
  // Retrieve an array which contains the path pieces.
  $path_args = explode('/', $current_path);
  $menu_link_add_or_edit_optimize = FALSE;
  $menu_name = '';

  if ($route_match == 'entity.menu.add_link_form' && isset($path_args[6])) {
    if ($path_args[4] == 'manage' && $path_args[6] == 'add') {
      $menu_link_add_or_edit_optimize = TRUE;
      $menu_name = $path_args[5] . ':';
    }
  }

  if ($route_match == 'entity.menu_link_content.canonical' && isset($path_args[6])) {
    if ($path_args[4] == 'item' && $path_args[6] == 'edit' && is_numeric($path_args[5])) {
      $mlid = $path_args[5];
      $link = AgriAdminHelper::getMenuLinkFromMlid($mlid);
      $menu_name = $link->getMenuName() . ':';
      // Always disable other menu items, speeds up logic for James logic.
      $menu_link_add_or_edit_optimize = TRUE;
      // $current_user = \Drupal::currentUser();
      // $current_user_id = $current_user->id();
      // $roles = $current_user->getRoles();
      // if (!in_array('administrator', $roles)) {
      // // Only non-Administrators should see the optimized menu for menu link EDIT
      // because we want administrators to be able to move this link around if they wish.
      // $menu_link_add_or_edit_optimize = TRUE;
      // }
    }
  }
  if ($menu_link_add_or_edit_optimize) {
    foreach ($form['menu_parent']['#options'] as $key => &$value) {
      if (strpos($key, $menu_name) === FALSE) {
        unset($form['menu_parent']['#options'][$key]);
      }
      else {
        // Check interface lang code, if english, look for 'disabled' value.
        // Then if NOT disabled, call logic or function.
        // Check interface lang code, if french, look for 'désactivé' value
        // Then if NOT désactivé, call logic or function.
        $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
        if ($langcode == 'en' && strpos($value, 'disabled') == FALSE) {
          $keyarray = explode(":", $key);
          if (count($keyarray) > 2) {
            if (AgriAdminHelper::isLinkFrenchOnly($keyarray[2])) {
              unset($form['menu_parent']['#options'][$key]);
            }
          }
        }
        else {
          if ($langcode == 'fr' && strpos($value, 'désactivé') == FALSE) {
            $keyarray = explode(":", $key);
            if (count($keyarray) > 2) {
              if (AgriAdminHelper::isLinkEnglishOnly($keyarray[2])) {
                unset($form['menu_parent']['#options'][$key]);
              }
            }
          }
        }
      }
    }
  }
  // @todo END OF MENU EDIT/ADD LINK OPTIMISATION.
  foreach ($form['menu_parent']['#options'] as $key => &$value) {
    if (strpos($value, '-- ') == 0) {
      // $value =  substr($value,0, 3) . 'level 1. ' . substr( $value,3, strlen($value)) ;
      $form['menu_parent']['#options_attributes'][$key]['class'] = ['class' => 'menu_tree-leve-1'];
    }
    else {
      if (strpos($value, '---- ') == 0) {
        // $value =  substr($value,0, 5) . 'level 2. ' . substr( $value,5, strlen($value)) ;
        $form['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-2 glyphicon';
      }
      else {
        if (strpos($value, '------ ') == 0) {
          // $value =  substr($value,0, 7) . 'level 3. ' . substr( $value,7, strlen($value)) ;
          $form['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-3';
        }
        else {
          if (strpos($value, '-------- ') == 0) {
            // $value =  substr($value,0, 9) . 'level 4. ' . substr( $value,9, strlen($value)) ;
            $form['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-4';
          }
          else {
            if (strpos($value, '---------- ') == 0) {
              // $value =  substr($value,0, 11) . 'level 5. ' . substr( $value,11, strlen($value)) ;
              $form['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-5';
            }
            else {
              if (strpos($value, '------------ ') == 0) {
                // $value =  substr($value,0, 13) . 'level 6. ' . substr( $value,11, strlen($value)) ;
                $form['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-6';
              }
            }
          }
        }
      }
    }
  }
}

/**
 * Implements hook_mail().
 */
function agri_admin_mail($key, &$message, $params) {
  switch ($key) {
    case 'mac_feedback':
    case 'agri_admin_mac_feedback':
      $subject = $params['subject'];
      $message['format'] = 'text/html';
      $message['content_type'] = 'text/html';
      $message['charset'] = 'UTF-8';
      $message['subject'] = $subject;
      $message['body'][] = new FormattableMarkup($params['message'], []);
      break;

    default:
      break;
  }

}

/**
 * Implements hook_file_validate().
 */
function agri_admin_file_validate(FileInterface $file) {
  // Check if the filehash configuration setting allow the duplicate file or not.
  if (!(\Drupal::config('filehash.settings')->get('dedupe'))) {
    // If filehash allows the duplicate file, we will provide the warning message when the duplicate file occurs.
    agri_admin_validate_dedupe_warning($file);
  }
}

/**
 * Checks that file is not a duplicate.
 */
function agri_admin_validate_dedupe_warning(FileInterface $file) {
  $warnings = [];
  $warning = '';
  $langId = \Drupal::languageManager()->getCurrentLanguage()->getId();
  if (!$file->id()) {
    foreach (agri_admin_algos() as $algo) {
      $query = \Drupal::database()->select('filehash');
      $query->addField('filehash', 'fid');
      $query->condition($algo, $file->filehash[$algo]);
      $query->range(0, 1);
      if ($fid = $query->execute()->fetchField()) {
        if (\Drupal::currentUser()->hasPermission('access files overview')) {
          try {
            $url = Url::fromRoute('view.files.page_2', ['arg_0' => $fid], ['attributes' => ['target' => '_blank']]);
            $filename = Link::fromTextAndUrl(File::load($fid)->label(), $url)->toString();
            if ($langId == 'en') {
              $warning = Markup::create('This file has already been uploaded as ' . $filename . '.');
            }
            else {
              $warning = Markup::create('Ce fichier a déjà été téléchargé en tant que ' . $filename . '.');
            }
          }
          catch (Exception $e) {
            // Maybe the view was disabled?
            \Drupal::messenger()->addWarning($e->getMessage(), TRUE);
          }
        }
        else {
          if ($langId == 'en') {
            $warning = 'This file has already been uploaded.';
          }
          else {
            $warning = 'Ce fichier a déjà été téléchargé.';
          }
        }
        array_push($warnings, $warning);
        break;
      }
    }
  }
  // Output all warning messages.
  foreach ($warnings as $msg) {
    \Drupal::messenger()->addWarning($msg, TRUE);
  }
  return [];
}

/**
 * Returns array of enabled hash algorithms.
 */
function agri_admin_algos() {
  return array_diff(\Drupal::config('filehash.settings')->get('algos'), [0]);
}

/**
 * Implements agri_admin_form_views_exposed_form_alter hook.
 */
function agri_admin_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $view = $form_state->getStorage('view');

  if ($view['view']->id() == 'content') {
    if (isset($form['type']['#options'])) {
      // Ensure that "- Any -" is 'first', and the other type options are in alphanum order.
      ksort($form['type']['#options']);
    }
  }
}
