<?php

use \Drupal\agri_admin\AgriAdminHelper;
use \Drupal\Core\File\FileSystemInterface;
use \Drupal\field\Entity\FieldStorageConfig;
use \Drupal\field\Entity\FieldConfig;
use \Drupal\media\Entity\Media;
use \Drupal\taxonomy\Entity\Term;

/**
 * @file
 * Install, update and uninstall functions for the Agri Admin module.
 */

/**
 * Implements hook_install().
 */
function agri_admin_install() {
  \Drupal::service('module_installer')->install(['entity_translation_unified_form']);
}

/**
 * Implements hook_uninstall().
 */
function agri_admin_uninstall() {
}


/**
 * Implements hook_requirements().
 */
/*function agri_admin_requirements($phase) {
  $requirements = [];

  if ($phase == 'runtime') {
    $value = mt_rand(0, 100);
    $requirements['agri_admin_status'] = [
      'title' => t('Agri Admin status'),
      'value' => t('Agri Admin value: @value', ['@value' => $value]),
      'severity' => $value > 50 ? REQUIREMENT_INFO : REQUIREMENT_WARNING,
    ];
  }

  return $requirements;
}*/

/**
 * Force disabled menu links for 'page' nodes AND add menu link for custom block library.
 */
function agri_admin_update_8001() {
  // For Huan agrcms/d8#141
  $query = \Drupal::entityQuery('node')->condition('type', 'page')
    ->accessCheck(FALSE)
    ->condition('status', 1);
  $nids = $query->execute();
  $count_success = 0;
  foreach ($nids as $vid => $nid) {
    $result = \Drupal\agri_admin\AgriAdminHelper::disableMenuLinkByNid($nid, 'sidebar');
    if ($result !== FALSE) {
      $count_success++;
    }
  }

  // For Deepani issue #65 agrcms/d8#65.
  $item = \Drupal\menu_link_content\Entity\MenuLinkContent::create([
    'link' => ['uri' => 'internal:/admin/structure/block/block-content'],
    'title' => 'Custom block library',
    'menu_name' => 'admin',
    //'parent' => 'system.admin_structure',
    'parent' => 'system.admin_content',
  ]);
  $options['attributes']['class'] = ['creator-only agrisource-not-for-admin-link'];
  $item->link->options = $options;
  $item->save();
  return (string) "\n\r1) Updated menu links that link for $count_success basic pages and disabled those links as they are for breadcrumb only. \n\r2) Added new menu link for creators under the admin content menu.";
}


/**
 * Fix source / track elements on imported content.
 */
function agri_admin_update_8002() {
  // For Huan agrcms/d8#141
  $query = \Drupal::entityQuery('node')->condition('type', 'page')
    ->accessCheck(FALSE)
    ->condition('status', 1);
  $and1 = $query->orConditionGroup()
    ->accessCheck(FALSE)
    ->condition('body', '/track>', 'CONTAINS');
  $and2 = $query->orConditionGroup()
    ->accessCheck(FALSE)
    ->condition('body', '/source>', 'CONTAINS');
  $query->condition($and1)
    ->condition($and2);
  $nids = $query->execute();
  $count_success = 0;
  $node_storage = \Drupal::entityTypeManager()->getStorage('node');
  \Drupal::messenger()->addMessage("agri_admin_update_8002()", 'warning', TRUE);
  $num_updated = 0;
  $connection = \Drupal::database();
  foreach ($nids as $vid => $nid) {
    $node = $node_storage->load($nid);
    \Drupal::messenger()->addMessage("Use a self closing source / track tag for nid = $nid title = " . $node->getTitle(), 'warning', TRUE);
    $body_html = $node->body->value; 
    $self_closing = preg_replace('/<source(.*?)><\/source>/is', '<source$1 />', $body_html);
    $self_closing = preg_replace('/<track(.*?)><\/track>/is', '<track$1 />', $self_closing);
/*    $num_updated += $connection->update('node__body')
      ->fields([
        'body_value' => $self_closing,
      ])
      ->condition('entity_id', $nid, '=')
      ->condition('revision_id', $vid, '=')
      ->execute();*/
    $node->set('body', array('value' => $self_closing, 'format' => 'full_html', 'summary' => text_summary($self_closing)));
    $node->save();
    \Drupal::messenger()->addMessage("Saved $nid", 'warning', TRUE);
  }
//  \Drupal::messenger()->addMessage("Updated node__body body_value $num_updated time(s)", 'warning', TRUE);
}

/**
 * Add new menu link to the admin/content/moderated page (view) for creators.
 */
function agri_admin_update_8003() {
  // For Lakshman issue #169 agrcms/d8#169 .
  $item = \Drupal\menu_link_content\Entity\MenuLinkContent::create([
    'link' => ['uri' => 'internal:/admin/content/moderated'],
    'title' => 'Moderated Content',
    'menu_name' => 'admin',
    'parent' => 'system.admin_content',
  ]);
  $options['attributes']['class'] = ['creator-only agrisource-not-for-admin-link'];
  $item->link->options = $options;
  $item->save();
  return (string) "\n\r1) Created a new menu link that link to the admin/content/moderated view for creators under the admin content menu.";

}

//Uncomment this after next migration.
//function agri_admin_update_8004() {
//  agri_admin_update_8001();
//}


/**
 * Change node__field_created_by from string 25 to string 100.
 */
function agri_admin_update_8004() {
  $database = \Drupal::database();
  $table = 'node__field_created_by';
  $entity_type = 'node';
  $field_name = 'field_created_by';

  $field_storage = FieldStorageConfig::loadByName($entity_type, $field_name);

  if (is_null($field_storage)) {
    return;
  }

  $rows = NULL;

  if ($database->schema()->tableExists($table)) {
    // The table data to restore after the update is completed.
    $rows = $database->select($table, 'n')
      ->fields('n')
      ->execute()
      ->fetchAll();
  }

  $new_fields = array();

  // Use existing field config for new field.
  foreach ($field_storage->getBundles() as $bundle => $label) {
    $field = FieldConfig::loadByName($entity_type, $bundle, $field_name);
    $new_field = $field->toArray();
    $new_field['field_type'] = 'string';
    $new_field['settings'] = array();

    $new_fields[] = $new_field;
  }

  // Deleting field storage which will also delete bundles(fields).
  $new_field_storage = $field_storage->toArray();
  $new_field_storage['type'] = 'string';
  $new_field_storage['settings'] = array(
    'max_length' => 100,
    'is_ascii' => FALSE,
    'case_sensitive' => FALSE,
  );

  $field_storage->delete();

  // Purge field data now to allow new field and field_storage with same name
  // to be created. You may need to increase batch size.
  field_purge_batch(10);

  // Create new field storage.
  $new_field_storage = FieldStorageConfig::create($new_field_storage);
  $new_field_storage->save();

  // Create new fields.
  foreach ($new_fields as $new_field) {
    $new_field = FieldConfig::create($new_field);
    $new_field->save();
  }

  // Restore existing data in the same table.
  if (!is_null($rows)) {
    foreach ($rows as $row) {
      $database->insert($table)
        ->fields((array) $row)
        ->execute();
    }
  }

}

/**
 * Force menu link disable.
 */
function agri_admin_update_8005() {
  // For Huan agrcms/d8#141
  $query = \Drupal::entityQuery('node')->condition('type', 'page')
    ->accessCheck(FALSE)
    ->condition('status', 1);
  $nids = $query->execute();
  $count_success = 0;
  foreach ($nids as $vid => $nid) {
    $result = \Drupal\agri_admin\AgriAdminHelper::disableMenuLinkByNid($nid, 'sidebar');
    if ($result !== FALSE) {
      $count_success++;
    }
  }
}


/**
 * Search engine optimisation, canonical url for home page should be https://domain/en and https://domain/fr for google seo.
 */
function agri_admin_update_8006() {
  $config = \Drupal::config('system.site');
  $front_uri = $config->get('page.front');
  $nid = str_replace('/node/', '', $front_uri);

  $node = \Drupal::entityTypeManager()->getStorage('node')->load($nid);
  $metatags = unserialize($node->get('field_meta_tags')->value);
  $metatags['canonical_url'] = 'https://agriculture.canada.ca/en';
  $node->set('field_meta_tags', serialize($metatags));
  $node->save();

  $node_fr = $node->getTranslation('fr');
  $metatags_fr = unserialize($node_fr->get('field_meta_tags')->value);
  $metatags_fr['canonical_url'] = 'https://agriculture.canada.ca/fr';
  $node_fr->set('field_meta_tags', serialize($metatags_fr));
  $node_fr->save();
}

/**
 * Import campaign example images into AAFC for usage with campaign placeholders.
 */
function agri_admin_update_8007() {

  $vid = 'media_category';
  $term_name = 'Campaign Example';
  $term_id = NULL;
  $term = NULL;

  $terms = \Drupal::entityTypeManager()
  ->getStorage('taxonomy_term')
  ->loadByProperties([
    'vid' => $vid,
    'name' =>$term_name,
  ]);
  if (empty($terms)) {
    $term = Term::create([
      'vid' => $vid,
      'name' => $term_name,
      'langcode' => 'en',
      'parent' => [],
    ]);

    $term->enforceIsNew();
    $term->save();
    $term_id = $term->id();
  }
  if (empty($term)) {
    $terms = \Drupal::entityTypeManager()
    ->getStorage('taxonomy_term')
    ->loadByProperties([
      'vid' => $vid,
      'name' =>$term_name,
    ]);
    foreach ($terms as $term_item) {
      $term_id = $term_item->id();
      $term = $term_item;
      // Done, exit immediately.
      break;
    }
  }
  $uri_path = 'public://campaign/example';
  \Drupal::service('file_system')->prepareDirectory($uri_path, FileSystemInterface::CREATE_DIRECTORY);
  $image_names = [
    'wl-web-top-banner-1920x300-EN.jpg',
    'wl-web-top-banner-1920x300-FR.jpg',
    'wl-web-top-banner-960x300-EN.jpg',
    'wl-web-top-banner-960x300-FR.jpg',
    'wl-web-top-banner-500x250-EN.jpg',
    'wl-web-top-banner-500x250-FR.jpg',
    'calendar-events-EN.jpg',
    'calendar-events-FR.jpg',
    'winterlude-national-ice-carving-championship-EN.jpg',
    'winterlude-national-ice-carving-championship-FR.jpg',
    'winterlude-olg-logo-450x450-EN.png',
    'winterlude-olg-logo-450x450-FR.png',
    'winterlude-sites-EN.jpg',
    'winterlude-sites-FR.jpg',
    'icon-facebook-white-EN.png',
    'icon-facebook-white-FR.png',
    'icon-instagram-white-EN.png',
    'icon-instagram-white-FR.png',
    'icon-twitter-white-EN.png',
    'icon-twitter-white-FR.png',
    'icon-youtube-white-EN.png',
    'icon-youtube-white-FR.png',
    'Timhortons450x450-EN.jpg',
    'Timhortons450x450-FR.jpg',
    'WL2022_WelcomePageDeco_TopDarkBlue-EN.jpg',
    'WL2022_WelcomePageDeco_TopDarkBlue-FR.jpg'
  ];
  foreach ($image_names as $image_name) {
    $langcode = 'en';
    if (strpos($image_name,'-FR.jpg') > 0) {
      $langcode = 'fr';
    }
    $image_selector = substr($image_name, 1);
    if (AgriAdminHelper::getCampaignImageUuidAndEntityId($uuid, $entity_id, $image_selector)) {
      // This image already exists, continue without importing it twice.
      AgriAdminHelper::addToLog($image_name . ' was previously imported, skipping', TRUE);
      continue;
    }
    $path_to_agri_admin = \Drupal::service('extension.list.module')->getPath('agri_admin');
    $image_data = file_get_contents(DRUPAL_ROOT . '/' . $path_to_agri_admin . '/campaign/images/' . $image_name);
    AgriAdminHelper::addToLog(DRUPAL_ROOT . '/' . $path_to_agri_admin . '/campaign/images/' . ' debug image path');
    $file_repository = \Drupal::service('file.repository');

    $image = $file_repository->writeData($image_data, "public://campaign/example/" . $image_name, FileSystemInterface::EXISTS_REPLACE);

    $alt_text = 'Example campaign media alt attribute for ' . $image_name;
    $title_text = 'Example media title attribute for ' . $image_name;
    if ($langcode == 'fr') {
      $alt_text = 'Campaigne exemple alt pour ' . $image_name;
      $title_text = 'Campaigne media titre exemple pour ' . $image_name;
    }
    $image_media = Media::create([
      'name' => $image_name,
      'bundle' => 'image',
      'uid' => \Drupal::currentUser()->id(),
      'langcode' => $langcode,
      'status' => 1,
      'image' => [
        'target_id' => $image->id(),
         'alt' => $alt_text,
         'title' => $title_text,
      ],
      'field_media_in_library' => TRUE,
    ]);
    $image_media->set('field_aafc_category', [$term]);

    AgriAdminHelper::addToLog($image_name . ' created for image with pattern langcode ' . $langcode, TRUE);
    $image_media->save();
  }

}



/**
 * Import topic image, rename it to for the new special title 825x200 px.
 */
function agri_admin_update_10001() {
  $url='https://design.canada.ca/coded-layout/images/theme-topic-img-825x200.jpg';
  $image_name = "special_title825x200.png";
  $destination_path = DRUPAL_ROOT . '/sites/default/files/legacy/' . $image_name;
  if (file_put_contents($destination_path,file_get_contents($url))) {
    $msg = "agri_admin_update_10001() $url for special title downloaded successfully";
    AgriAdminHelper::addToLog($msg, TRUE);
    AgriAdminHelper::createMediaEntity($image_name, 'legacy');
  }
  else {
    AgriAdminHelper::addError('ERROR in agri_admin_update_10001(), a problem downloading the 825x200 special title image.');
  }
}



/**
 * Make sure all nodes have special and campaign saved so we can filter by it.
 */
/*function agri_admin_update_11999() {

  $nodeStorage = \Drupal::entityTypeManager()->getStorage('node');

  $nids = $nodeStorage->getQuery()->execute();
  if (count($nids) > 0) {
    AgriAdminHelper::addToLog(count($nids) . ' nodes will be processed immediately.', TRUE);
  }
  $idx = 0;
  //content_moderation_notifications.content_moderation_notification.published_notification status false -y
  $config_factory = \Drupal::configFactory();
  $config = $config_factory->getEditable('content_moderation_notifications.content_moderation_notification.published_notification');
  // Disable notifications during cron run, 2500 emails to avoid.
  $config->set('status', FALSE);
  $config->save(TRUE);
  drupal_flush_all_caches();
  $error_once = FALSE;
  foreach ($nids as $nid) {
    $idx++;
    if ($idx % 50 == 0) {
      AgriAdminHelper::addToLog($idx . ' nodes have been processed.', TRUE);
    }
    $node = \Drupal::entityTypeManager()->getStorage('node')->load($nid);
    if ($node->bundle() == 'dir_listing') {
      AgriAdminHelper::addToLog($nid . " is a dir_listing node, skipped", TRUE);
      continue;
    }
    if (!$node->hasField('field_campaign') || !$node->hasField('field_large') || !$node->hasField('field_special')) {
      // Re-enable notifications in case of failure/error.
      $error_once = TRUE;
      $config->set('status', TRUE);
      $config->save(TRUE);
      AgriAdminHelper::addWarning('WARNING, field_campaign does not yet exist, run this command:');
      AgriAdminHelper::addWarning('drush ev "Drupal::keyValue(\'system.schema\')->set(\'agri_admin\', (int) 8007)";');
      AgriAdminHelper::addError('ERROR in agri_admin_update_8008() see above messages.');
      break;
    }
    if ($node->get('field_campaign')->value) {
      $node->set('field_campaign', TRUE);
    }
    else {
      $node->set('field_campaign', FALSE);
    }
    if ($node->get('field_special')->value) {
      $node->set('field_special', TRUE);
    }
    else {
      $node->set('field_special', FALSE);
    }
    if ($node->get('field_large')->value) {
      $node->set('field_large', TRUE);
    }
    else {
      $node->set('field_large', FALSE);
    }
    if ($error_once) {
      $error_once = FALSE;
      // Re-disable notifications.
      $config->set('status', FALSE);
      $config->save(TRUE);
      drupal_flush_all_caches();
    }
    $node->save(); // Trigger save, this will store field_campaign .
  }
  // Re-enable notifications.
  $config->set('status', TRUE);
  $config->save(TRUE);
  //content_moderation_notifications.content_moderation_notification.published_notification status true -y
  if (count($nids) > 0) {
    AgriAdminHelper::addToLog(count($nids) . ' total nodes were processed.', TRUE);
  }

}
*/

