<?php

/**
 * @file
 * AAFC theme preprocess hooks and more.
 */

use Drupal\Core\Render\Markup;
use Drupal\agri_admin\UtilsBlock;
use Drupal\bootstrap\Bootstrap;
use Drupal\agri_admin\Utils;
use Drupal\node\NodeInterface;


/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function aafctheme_theme_suggestions_block_alter(&$suggestions, $variables) {
  // Load theme suggestions for blocks from parent theme.
  // https://www.drupal.org/project/wxt/issues/3310485#comment-14715969
  for ($i = 0; $i < count($suggestions); $i++) {
    if (isset($suggestions[$i]) && str_contains($suggestions[$i], 'aafctheme_')) {
      $new_suggestions = [
        str_replace('aafctheme_', '', $suggestions[$i]),
        str_replace('aafctheme_', 'wxt_bootstrap_', $suggestions[$i]),
      ];
      array_splice($suggestions, $i, 0, $new_suggestions);
      $i += 2;
    }
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function aafctheme_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  $moduleHandler = \Drupal::service('module_handler');

  if ($moduleHandler->moduleExists('wxt_ext_book')) {
    $node = \Drupal::routeMatch()->getParameter('node');

    if ($node instanceof NodeInterface) {
      if (!empty($node->book) && $node->book['bid'] != 0) {
        /** @var \Drupal\wxt_library\LibraryService $wxt */
        $wxt = \Drupal::service('wxt_library.service_wxt');
        $wxt_active = $wxt->getLibraryName();

        if ($node->book['bid'] == $node->id()) {
          // Theme book index page
          $suggestions[] = $variables['theme_hook_original'] . '__book_index';
          $suggestions[] = $variables['theme_hook_original'] . '__' . $wxt_active . '__book_index';
        }
        else {
          // Theme book child page
          $suggestions[] = $variables['theme_hook_original'] . '__book_page';
          $suggestions[] = $variables['theme_hook_original'] . '__' . $wxt_active . '__book_page';
        }
      }
    }
  }
}

/**
 * @file
 * WxT Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */

/**
 * Implements hook_preprocess_html().
 */
function aafctheme_preprocess_html(&$variables) {
  $route_match = Utils::getRouteName();

  $variables['four_oh_four'] = FALSE;
  if ($route_match == 'system.404') {
    $variables['four_oh_four'] = TRUE;
  }

  $head_title = '';
  if (isset($variables['head_title']['title'])) {
    $head_title = $variables['head_title']['title'];
  }
  $some_slogan = ' | Agriculture and Agri-Food Canada (AAFC)';
  if (stripos($head_title, $some_slogan) > 2) {
    $head_title = str_replace($some_slogan, ' - agriculture.canada.ca', $head_title);
  }
  $some_slogan = ' | Agriculture et Agroalimentaire Canada (AAC)';
  if (stripos($head_title, $some_slogan) > 2) {
    $head_title = str_replace($some_slogan, ' - agriculture.canada.ca', $head_title);
  }
  $some_slogan = ' | Agriculture and Agri-Food Canada Dev';
  if (stripos($head_title, $some_slogan) > 2) {
    $head_title = str_replace($some_slogan, ' - agriculture.canada.ca DEV', $head_title);
  }
  $some_slogan = ' | Agriculture et Agroalimentaire Canada Dev';
  if (stripos($head_title, $some_slogan) > 2) {
    $head_title = str_replace($some_slogan, ' - agriculture.canada.ca DEV', $head_title);
  }
  $variables['head_title']['title'] = $head_title;

  $current_path = \Drupal::service('path.current')->getPath();
  $langId = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $variables['langID'] = $langId;
  $theme = Bootstrap::getTheme();
  $themedir = $theme->getPath();
  $variables['current_path'] = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);
  // Add class attribute (current role names) to the body class (for styling).
  // Ex: administrator, comms, reviewer, anonymous.
  $roles = \Drupal::currentUser()->getRoles();
  foreach ($roles as $role_name) {
    $variables['attributes']['class'][] = $role_name;
  }

  // Begin logic to grab moderation state and add it to the body class for styling.
  // This section is required for view node identify draft revisions as 'pink'.
  // Corresponding draft pink css is in css/style.scss.
  $variables['current_path'] = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);
  // Add node id to the body class.
  $node = \Drupal::routeMatch()->getParameter('node');
  $node_revision = \Drupal::routeMatch()->getParameter('node_revision');
  $routeMatchParams = \Drupal::routeMatch()->getParameters();
  $nid = 0;
  $vid = 0;
  $revision_is_object = FALSE;
  $archived = '';
  if ($node) {
    // Workaround for https://www.drupal.org/project/drupal/issues/2730631 .
    // Workaround for inconsistent router behaviour, see comments in issue 2730631.
    // @todo , follow up on issue 2730631.
    $published = 'published-yes';
    $is_unpublished = '';
    $is_pending_draft = '';
    $nodeType = '';
    $node_storage = \Drupal::entityTypeManager()->getStorage('node');

    if (is_string($node) && is_numeric($node)) {
      $nid = $node;
    }
    elseif (gettype($node) == 'object') {
      $nid = $node->id();
      $nodeType = $node->getType();
      $vid = $node->getRevisionId();
    }

    $variables['attributes']['class'][] = 'node-' . $nid;

    if (is_string($node_revision) && is_numeric($node_revision)) {
      $vid = $node_revision;
    }

    if (gettype($node_revision) == 'object') {
      $revision_is_object = TRUE;
      $vid = $node_revision->getRevisionId();
    }

    if ($vid == 0 && gettype($node_revision) == 'object') {
      // Get the revision id.
      $vid = $node->getRevisionId();
    }

    if ($vid) {
      // Load the revision.
      $this_revision = $node_revision;
      if (!$revision_is_object) {
        $this_revision = \Drupal::entityTypeManager()->getStorage('node')->loadRevision($vid);
      }
      if ($this_revision->hasTranslation($langId)) {
        // Get current language revision.
        $this_revision = $this_revision->getTranslation($langId);
      }
      // Get the revisions moderation state.
      $this_revision_state = $this_revision->get('moderation_state')->getString();
      if ($this_revision_state != 'published' && $this_revision_state != 'archived') {
        $published = 'published-no';
        $is_unpublished = 'is-unpublished';
        // Determine if revision is pending-draft (unpublished with previous published revision).
        if (!$this_revision->isDefaultRevision()) {
          // Since this is NOT the default revision, it means that the current revision state is not draft.
          // So given our workflow configuration we can assume that this is a 'pending-draft'.
          $is_pending_draft = 'pending-draft';
        }
      }
      if ($this_revision_state == 'archived') {
        $published = 'published-no-is-archived';
        $archived = 'archived';
      }
      $nodeType = $this_revision->getType();
    }

    if (!empty($nodeType)) {
      $variables['attributes']['class'][] = $nodeType;
    }
    $variables['attributes']['class'][] = 'node-' . $nid;
    // Add node published status to body class.
    $variables['attributes']['class'][] = $published;
    if (!empty($archived)) {
      $variables['attributes']['class'][] = $archived;
    }
    if (!empty($is_unpublished)) {
      $variables['attributes']['class'][] = $is_unpublished;
    }
    if (!empty($is_pending_draft)) {
      $variables['attributes']['class'][] = $is_pending_draft;
    }

  }
  // Get original url (/webform/yourfeedback_programsandservices) from url alias mapping info.
  if (isset($variables['page']['#attached']['http_header'][0][1])) {
    $patten = '/\/webform\/yourfeedback_programsandservices>/';
    $urlaliasmapping = $variables['page']['#attached']['http_header'][0][1];
    if (preg_match($patten, $urlaliasmapping)) {
      // Add custom - feedback_programsandservices_webform css class.
      $variables['attributes']['class'][] = 'webform_feedback_programsandservices';
    }
  }
  // Get original url (/webform/aafc_generic_contact_form) from url alias mapping info.
  if (isset($variables['page']['#attached']['http_header'][0][1])) {
    $patten = '/\/webform\/aafc_generic_contact_form>/';
    $urlaliasmapping = $variables['page']['#attached']['http_header'][0][1];
    if (preg_match($patten, $urlaliasmapping)) {
      // Add custom - feedback_programsandservices_webform css class.
      $variables['attributes']['class'][] = 'webform_generic_contactform';
    }
  }
  // End of logic to grab moderation state and add it to the body class for styling.
  $host = \Drupal::request()->getHost();
  $prod = FALSE;
  if (stripos($host, 'www-ep.agr.gc.ca') !== FALSE || stripos($host, 'agriculture.canada.ca') !== FALSE) {
    $prod = TRUE;
  }
  // Adobe Analytics JS library.
  if (\Drupal::currentUser()->isAnonymous() && $prod) {
    $variables['#attached']['library'][] = 'aafctheme/aafctheme-externaladobetmprodjs';
  }
  else {
    $variables['#attached']['library'][] = 'aafctheme/aafctheme-externaladobetmstagingjs';
  }

  // Invitation Manager CSS and JS library.
  if (\Drupal::currentUser()->isAnonymous()) {
    $variables['#attached']['library'][] = 'aafctheme/aafctheme-invitationmanager';
  }

}

/**
 * Implments hook_preprocess_field().
 */
function aafctheme_preprocess_field(&$variables, $hook) {
  if ($variables['element']['#field_name'] == 'field_classification') {
    $block = UtilsBlock::getRendered('employment_classification_groups');
    $variables['empl_classification_block'] = $block;
  }
}

/**
 * Implements hook_preprocess_textarea().
 */
function aafctheme_preprocess_textarea(&$variables) {
  if (is_object($variables['attributes'])) {
    $attribute_obj = $variables['attributes'];
    $attr_array = $attribute_obj->toArray();
    if (isset($attr_array['aria-describedby'])) {
      if ($attr_array['aria-describedby'] == 'edit-body-0-summary--description') {
        $attribute_obj->removeAttribute('aria-describedby');
        $variables['attributes'] = $attribute_obj;
      }

      if ($attr_array['aria-describedby'] == 'edit-body-etuf-fr-0-summary--description') {
        $attribute_obj->removeAttribute('aria-describedby');
        $variables['attributes'] = $attribute_obj;
      }
    }
  }
}

function aafctheme_preprocess_input__button__submit(&$vars) {
  $route_name = Utils::getRouteName();
  $pass_validation = (strpos($route_name, 'view.print_all_steps_of_program_') === 0) ? TRUE : FALSE;
  if ($pass_validation && $vars['theme_hook_original'] == 'input__submit') {
    $label = (string) $vars['label'];
    // \Drupal\agri_admin\AgriAdminHelper::addToLog('debug? : <pre>' . print_r(array_keys($vars),TRUE) . '</pre>' , TRUE);
    if ($label == 'Appliquer aux éléments sélectionnés' || $label == 'Apply to selected items') {
      $label = t('Download PDF');
      $vars['label'] = $label;
    }
  }
}

/**
 * Implements hook_preprocess_input().
 */
function aafctheme_preprocess_input(&$variables) {
  if (\Drupal::currentUser()->isAnonymous()) {
    if (is_object($variables['attributes'])) {
      $attribute_obj = $variables['attributes'];
      $attr_array = $attribute_obj->toArray();
      if (isset($attr_array['id'])) {
        if ($attr_array['id'] == 'edit-field-date-closing-0-value-date') {
          $attribute_obj->removeAttribute('aria-required');
          $variables['attributes'] = $attribute_obj;
        }

        if ($attr_array['id'] == 'edit-field-posted-0-value-date') {
          $attribute_obj->removeAttribute('aria-required');
          $variables['attributes'] = $attribute_obj;
        }
      }
    }
  }
}

/**
 * Implements hook_preprocess_field_multiple_value_form().
 */
function aafctheme_preprocess_field_multiple_value_form(&$vars) {
  if (!\Drupal::currentUser()->isAnonymous()) {
    return;
  }
  // Anonymous only logic below.
  // Remove weight option for multivalue fields.
  if (isset($vars['table']['#tabledrag'])) {
    unset($vars['table']['#tabledrag']);
    array_pop($vars['table']['#header']);
    foreach ($vars['table']['#rows'] as &$row) {
      foreach ($row['data'] as $key => $rowrowdata) {
        if (!$rowrowdata['data']) {
          unset($row['data'][$key]);
        }
      }
    }
  }
}

/**
 * Implements hook_preprocess_fieldset().
 */
function aafctheme_preprocess_fieldset(&$variables) {
  unset($variables['attributes']['required']);
  unset($variables['attributes']['aria-required']);
  unset($variables['attributes']['aria-invalid']);
}

/**
 * Implements hook_preprocess_form_element_label().
 */
function aafctheme_preprocess_form_element_label(&$variables) {
  if (\Drupal::currentUser()->isAnonymous()) {
    if (isset($variables['attributes']['for']) && $variables['attributes']['for']) {
      if ($variables['attributes']['for'] == 'edit-advanced') {
        // This squelches w3c error for label that has no element.
        // Since we have removed edit-advanced section we also adjust its label.
        unset($variables['element']);
        unset($variables['attributes']['for']);
        unset($variables['attributes']['class']);
        $variables['attributes']['class'] = 'sr-only';
      }
    }
  }
}

/**
 * Prevents quickedit javascript crash for this image style.
 */
function aafctheme_preprocess_media(&$vars) {
  // Fixing the media missed the quick edit attribute.
  if (!empty($vars["elements"]["#media"])) {
    $media = $vars["elements"]["#media"];
    $type = $media->getEntityType()->id();
    $id = $media->id();

    if (!isset($vars['attributes']['data-quickedit-entity-id'])) {
      $vars['attributes']['data-quickedit-entity-id'] = $type . '/' . $id;
    }
  }
}

/**
 * Prevents quickedit javascript crash for this image style.
 */
function aafctheme_preprocess_media__image__w0520px(&$vars) {
  // Fixing the media missed the quick edit attribute.
  if (!empty($vars["elements"]["#media"])) {
    $media = $vars["elements"]["#media"];
    $type = $media->getEntityType()->id();
    $id = $media->id();

    if (!isset($vars['attributes']['data-quickedit-entity-id'])) {
      $vars['attributes']['data-quickedit-entity-id'] = $type . '/' . $id;
    }
  }
}

/**
 * Implements hook_preprocess_page().
 */
function aafctheme_preprocess_page(&$vars) {
  /* hide view and lastest version TABS in the page content */
  $current_uri = \Drupal::request()->getRequestUri();
  $regex_token = '/\/latest\?auHash=([a-zA-Z]|[0-9]|[_]|[-]){43}/';
  if (preg_match($regex_token, $current_uri)) {
    if (\Drupal::currentUser()->isAnonymous() && $vars['page']['#type'] == 'page') {
      $langId = \Drupal::languageManager()->getCurrentLanguage()->getId();
      if ($langId == 'en') {
        $patten = '/<nav class="tabs mrgn-tp-md mrgn-bttm-md" aria-label="Tabs">/';
        $replacement = '<nav class="tabs mrgn-tp-md mrgn-bttm-md" style="display: none;" aria-label="Tabs">';
      }
      else {
        $patten = '/<nav class="tabs mrgn-tp-md mrgn-bttm-md" aria-label="Onglets">/';
        $replacement = '<nav class="tabs mrgn-tp-md mrgn-bttm-md" style="display: none;" aria-label="Onglets">';
      }
      $content = $vars['page']['content']['system_main']['#markup'];
      if (isset($content)) {
        $content = preg_replace($patten, $replacement, $content);
        if (isset($content)) {
          $vars['page']['content']['system_main']['#markup'] = Markup::create($content);
        }
      }
    }
  }
  $node = \Drupal::routeMatch()->getParameter('node');
  $node_storage = \Drupal::entityTypeManager()->getStorage('node');
  $vars['large_mode'] = FALSE;
  $vars['campaign_mode'] = FALSE;
  if (is_string($node) && is_numeric($node)) {
    $nid = $node;
    $node = $node_storage->load($nid);
  }
  if (is_object($node) && $node->hasField('field_large')) {
    $large_mode = $node->get('field_large')->value;
    $vars['large_mode'] = $large_mode;
  }
  if (is_object($node) && $node->hasField('field_campaign')) {
    if ($node->get('field_campaign')->value) {
      // If campaign is true, force large mode also.
      $large_mode = $node->get('field_campaign')->value;
      $vars['large_mode'] = $large_mode;
      $campaign_mode = $node->get('field_campaign')->value;
      $vars['campaign_mode'] = $campaign_mode;
    }
  }
}

/**
 * Implements hook_preprocess_page_title__node__1__gcweb().
 */
function aafctheme_preprocess_page_title__node__1__gcweb(&$vars) {
  // Handle special_title logic.
  aafctheme_preprocess_page_title__gcweb($vars);
}

/**
 * Implements hook_preprocess_page_title__gcweb().
 */
function aafctheme_preprocess_page_title__gcweb(&$vars) {
  $node = \Drupal::routeMatch()->getParameter('node');
  $node_storage = \Drupal::entityTypeManager()->getStorage('node');
  $vars['special_title'] = FALSE;
  $vars['campaign_title'] = FALSE;
  if (is_string($node) && is_numeric($node)) {
    $nid = $node;
    $node = $node_storage->load($nid);
  }
  if (is_object($node) && $node->hasField('field_special')) {
    $special_title = $node->get('field_special')->value;
    $vars['special_title'] = $special_title;
  }
  if (is_object($node) && $node->hasField('field_campaign')) {
    if ($node->get('field_campaign')->value) {
      // If campaign is true, force special title mode also.
      $special_title = $node->get('field_campaign')->value;
      $vars['special_title'] = $special_title;
      $campaign_title = $node->get('field_campaign')->value;
      $vars['campaign_title'] = $campaign_title;
    }
  }

}

/**
 * Implements hook_preprocess_menu__brand_fr().
 */
function aafctheme_preprocess_menu__brand_fr(&$vars) {
  $node = \Drupal::routeMatch()->getParameter('node');
  $node_storage = \Drupal::entityTypeManager()->getStorage('node');
  if (is_string($node) && is_numeric($node)) {
    $nid = $node;
    $node = $node_storage->load($nid);
  }
  $vars['campaign_mode'] = FALSE;
  if (is_object($node) && $node->hasField('field_campaign')) {
    if ($node->get('field_campaign')->value) {
      $campaign_mode = $node->get('field_campaign')->value;
      $vars['campaign_mode'] = $campaign_mode;
    }
    if (\Drupal::config('agri_admin.settings')->get('campaign_footer_branding')) {
      $vars['campaign_mode'] = FALSE;
    }
  }
}

/**
 * Implements hook_preprocess_menu__brand__gcweb().
 */
function aafctheme_preprocess_menu__brand__gcweb(&$vars) {
  $node = \Drupal::routeMatch()->getParameter('node');
  $node_storage = \Drupal::entityTypeManager()->getStorage('node');
  if (is_string($node) && is_numeric($node)) {
    $nid = $node;
    $node = $node_storage->load($nid);
  }
  $vars['campaign_mode'] = FALSE;
  if (is_object($node) && $node->hasField('field_campaign')) {
    if ($node->get('field_campaign')->value) {
      $campaign_mode = $node->get('field_campaign')->value;
      $vars['campaign_mode'] = $campaign_mode;
    }
    if (\Drupal::config('agri_admin.settings')->get('campaign_footer_branding')) {
      $vars['campaign_mode'] = FALSE;
    }
  }
}

/**
 * Implements hook_preprocess_region__header__gcweb().
 */
function aafctheme_preprocess_region__header__gcweb(&$vars) {
  $node = \Drupal::routeMatch()->getParameter('node');
  $node_storage = \Drupal::entityTypeManager()->getStorage('node');
  $vars['large_mode'] = FALSE;
  if (is_string($node) && is_numeric($node)) {
    $nid = $node;
    $node = $node_storage->load($nid);
  }
  if (is_object($node) && $node->hasField('field_large')) {
    $large_mode = $node->get('field_large')->value;
    $vars['large_mode'] = $large_mode;
  }

}

/**
 * Implements hook_preprocess_region__content_footer__gcweb().
 */
function aafctheme_preprocess_region__content_footer__gcweb(&$vars) {
  $node = \Drupal::routeMatch()->getParameter('node');
  $node_storage = \Drupal::entityTypeManager()->getStorage('node');
  $vars['large_mode'] = FALSE;
  $vars['campaign_mode'] = FALSE;
  if (is_string($node) && is_numeric($node)) {
    $nid = $node;
    $node = $node_storage->load($nid);
  }
  if (is_object($node) && $node->hasField('field_large')) {
    $large_mode = $node->get('field_large')->value;
    $vars['large_mode'] = $large_mode;
  }
  if (is_object($node) && $node->hasField('field_campaign')) {
    $campaign_mode = $node->get('field_campaign')->value;
    $vars['campaign_mode'] = $campaign_mode;
    $block = \Drupal\block\Entity\Block::load('aafctheme_datemodifiedblock');
    $vars['date_modified'] = \Drupal::entityTypeManager()
      ->getViewBuilder('block')
      ->view($block);
  }

}
