define({
  root: {
    "dailyForecastLabel": "Forecast Date: ",
    "dailyForecastDateSeparator": " to ",

    "loading": "Loading...",

    "regionLabel": "Region: ",
    "regionOptionNational": "National",
    "regionOptionAtlantic": "Atlantic",
    "regionOptionBc": "British Columbia",
    "regionOptionOnqc": "Ontario and Quebec",
    "regionOptionPrairies": "Prairies",

    "variableLabel": "Weather Variable: ",
    "variableOptionTemp": "Temperature",
    "variableOptionPrecip": "Precipitation",
    "variableOptionHeat": "Heat",
    "variableOptionWind": "Wind",

    "forecastPeriodLabel": "Forecast Period: ",
    "forecastPeriodOptionWeek1": "Week 1",
    "forecastPeriodOptionWeek2": "Week 2",
    "forecastPeriodOptionWeek3": "Week 3",
    "forecastPeriodOptionWeek4": "Week 4",
    "forecastPeriod2Weeks": "2 Weeks",

    "indexLabel": "Index: ",
    "probabilityLabel": "Probability of: ",

    "indexTitlePrefix": "Index Map: ",
    "probabilityTitlePrefix": "Probability of ",

    "legendTextAltTitle": "Description - Legend",
    "legendIndexDescription": "Colour overlays on this map symbolize forecast data pertaining to ${content} from ${range}",
    "legendIndexDescriptionContentTemp": "the number of days",
    "legendIndexDescriptionRangeTemp": "one to seven",
    "legendProbabilityDescription": "Colour overlays on this map symbolize the ${probability} from less than thirty percent to one hundred percent",
    "legendProbabilityDescriptionTemp": "occurrence",

    "downloadTitle": "Download links for the above maps: ",
    "downloadIndexNational": "Index maps for the National region",
    "downloadIndexAtlantic": "Index maps for the Atlantic region",
    "downloadIndexBc": "Index maps for the BC region",
    "downloadIndexOnqc": "Index maps for the ON & QC region",
    "downloadIndexPrairies": "Index maps for the Prairies region",
    "downloadProbNational": "Probability maps for the National region",
    "downloadProbAtlantic": "Probability maps for the Atlantic region",
    "downloadProbBc": "Probability maps for the BC region",
    "downloadProbOnqc": "Probability maps for the ON & QC region",
    "downloadProbPrairies": "Probability maps for the Prairies region",
    "downloadFormat": "PDF",
    "downloadSize": " ~2MB",
    "temp": "temperature",
    "precip": "precipitation",
    "heat": "heat",
    "wind": "wind",

    "pd": "Greatest Daily Precipitation",
    "p1d2_prob": "Daily precipitation above 2mm",
    "p1d10_prob": "Daily precipitation above 10mm",
    "p1d25_prob": "Daily precipitation above 25mm",
    "pw": "Total Precipitation",
    "pweek25_prob": "Total precipitation above 25mm",
    "pweek50_prob": "Total precipitation above 50mm",
    "pweek100_prob": "Total precipitation above 100mm",
    "p10d": "Greatest 10-day precipitation",
    "p10d_prob10": "10-day precipitation above 10mm",
    "p10d_prob100": "10-day precipitation above 100mm",
    "p10d_prob150": "10-day precipitation above 150mm",

    "ffd_warm": "Frost-free days for warm season crops (>0°C)",
    "ffd_warm_prob": "Frost for warm season crops (<0°C)",
    "ffd_cool": "Frost-free days for cool season/overwintering crops (>-2°C)",
    "ffd_cool_prob": "Frost for cool season/overwintering crops (<-2°C)",
    "dcw_warm": "Cool wave days for warm season crops (< 10°C)",
    "dcw_warm_prob": "Cool wave days for warm season crops (< 10°C)",
    "dcw_cool": "Cool wave days for cool season/overwintering crops (< 5°C)",
    "dcw_cool_prob": "Cool wave days for cool season/overwintering crops (<5°C)",
    "dhw_warm": "Heat wave days for warm season crops (>35°C)",
    "dhw_warm_prob": "Heat wave days for warm season crops (>35°C)",
    "dhw_cool": "Heat wave days for cool season crops (>30°C)",
    "dhw_cool_prob": "Heat wave days for cool season crops (>30°C)",
    "ifd_grow": "Ice freeze days (woody or herbaceous crops) during growing season (<-2°C)",
    "ifd_grow_prob": "Ice freeze days (woody or herbaceous crops) during growing season (<-2°C)",
    "ifd_herb_dorm":"Ice freeze days (herbaceous crops) in dormant period (<-15°C)",
    "ifd_herb_dorm_prob":"Ice freeze days (herbaceous crops) in dormant period (<-15°C)",
    "ifd_wood_dorm":"Ice freeze days (woody crops) in dormant period (<-30°C)",
    "ifd_wood_dorm_prob":"Ice freeze days (woody crops) in dormant period (<-30°C)",
    "ifd_herb_nogrow":"Ice freeze days (herbaceous crops) during non-growing season (<-5°C)",
    "ifd_herb_nogrow_prob":"Ice freeze days (herbaceous crops) during non-growing season (<-5°C)",
    "ifd_wood_nogrow":"Ice freeze days (woody crops) during non-growing season (<-10°C)",
    "ifd_wood_nogrow_prob":"Ice freeze days (woody crops) during non-growing season (<-10°C)",

    "egdd_warm": "Effective growing season degree days for warm season crops",
    "egdd_warm_175prob": "Effective growing season degree days above 175 for warm season crops",
    "egdd_warm_100prob": "Effective growing season degree days above 100 for warm season crops",
    "egdd_warm_250prob": "Effective growing season degree days above 250 for warm season crops",
    "egdd_cool": "Effective growing season degree days for cool season crops",
    "egdd_cool_100prob": "Effective growing season degree days above 100 for cool season crops",
    "egdd_cool_175prob": "Effective growing season degree days above 175 for cool season crops",
    "egdd_cool_250prob": "Effective growing season degree days above 250 for cool season crops",

    "drying": "Number of drying days",
    "drying_prob": "Drying day occurrence",
    "mdws": "Maximum wind speed",
    "mdws50_prob": "Maximum wind above 50km/h",
    "mdws70_prob": "Maximum wind above 70km/h",
    "mdws90_prob": "Maximum wind above 90km/h",
    "nswd": "Number of strong wind days",
    "nswd_prob": "Strong wind day occurrence",

    "legendNumberOfDays": "the number of days",
    "legendRange1Week": "one to seven",
    "legendRange2Weeks": "one to fourteen",
    "legendRangeWindSpeed": "less than thirty to above ninety kilometers per hour",
    "legendRangeEGDD": "from thirty-five to over two hundred and sixty",
    "legendAmountPrecipitation60mm": "zero millimeters to sixty millimeters",
    "legendAmountPrecipitation120mm": "zero millimeters to one hundred and twenty millimeters",
    "legendAmountPrecipitation20cm": "zero to twenty centimeters",
  },
  "fr": true
});